### ISSUE TITLE
Generated npm package has ///<reference> to non-existent files, causing build breaks

### ISSUE THREAD

**Issue by jkeech** [Microsoft/vsts-task-lib#10]
For instance, lib/toolrunner.js and d.ts/vso-task-lib.d.ts both have the following at the top of the file.

```
/// <reference path="../definitions/node.d.ts" />
/// <reference path="../definitions/Q.d.ts" />
```

Then, when I try to build a custom task using TypeScript that references this npm package, I get compile errors.

> src\Tasks\MyCustomTask\node_modules\vso-task-lib\d.ts\vso-task-lib.d.ts(1,1): error TS6053: File 'd:/git/src/Tasks/MyCustomTask/node_modules/vso-task-lib/definitions/node.d.ts' not found.
> src\Tasks\MyCustomTask\node_modules\vso-task-lib\d.ts\vso-task-lib.d.ts(2,1): error TS6053: File 'd:/git/src/Tasks/MyCustomTask/node_modules/vso-task-lib/definitions/Q.d.ts' not found.

I should be able to install the npm package and build against it successfully.

**Comment by TingluoHuang** [comment]
This should be fixed right now.
