### ISSUE TITLE
using PowerShell3 execution causes "Cannot process command because of one or more missing mandatory parameters"

### ISSUE THREAD

**Issue by ghowlett2020** [Microsoft/vsts-task-lib#107]
Hi,

I have a task using the following input...

```
 "inputs": [
     {
      "name": "NuGetServerEndpoint",
      "type": "connectedService:Generic",
      "label": "NuGet Server Endpoint",
      "required": true,
      "helpMarkDown": "The NuGet server generic endpoint."
    }
  ],
```

and in my PowerShell script have the corresponding Params

```
Param
(
	[Parameter(Mandatory=$true)]
	[string]$NuGetServerEndpoint
)
```

If i use "PowerShell" the task runs fine - however when i use "PowerShell3" i get the error as per the subject "Cannot process command because of one or more missing mandatory parameters"

Do i need a different type when using Powershell3? I have installed the ps module as per the documentation and when running locally "Invoke-VstsTaskScript -ScriptBlock { . .\MyTask.ps1 }" all works fine (except im asked for the parameter $NuGetServerEndpoint) despite the fact i declare it as...

```
$env:INPUT_NuGetServerEndpoint = "EP1"
$env:ENDPOINT_URL_EP1 = 'http://nuget.org'
$env:ENDPOINT_AUTH_EP1 = '{ "Parameters": { "UserName": "Some user", "Password": "Some password" }, "Scheme": "Some scheme" }'
$env:ENDPOINT_DATA_EP1 = '{ "Key1": "Value1", "Key2": "Value2" }'
```

Can you please provide some help on this?

Much appreciated
[ExampleFiles.zip.zip](https://github.com/Microsoft/vsts-task-lib/files/380499/ExampleFiles.zip.zip)

**Comment by ericsciple** [comment]
You need to use [Get-VstsInput](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/FullHelp/Get-VstsInput.md) to get the input, and Get-VstsEndpoint to get the endpoint.

I'm working on docs right now. Better getting started docs coming soon.

**Comment by ghowlett2020** [comment]
Many thanks - using Get-VstsInput works.

+1 for those documents :-)
