### ISSUE TITLE
.d.ts file being generated with the wrong module names

### ISSUE THREAD

**Issue by jkeech** [Microsoft/vsts-task-lib#11]
The vso-task-lib.d.ts file is being generated with 

```
declare module 'vso-task-lib/taskcommand' {
    ...
}
```

but the folder structure of the npm module is acutally vso-task-lib/**lib**/taskcommand.js. This means the generated .d.ts file should contain

```
declare module 'vso-task-lib/lib/taskcommand' {
    ...
}
```

in order for the module to be loaded by NodeJS via require('vso-task-lib/lib/taskcommand'). I think this should be a small fix to the gulpfile as part of the configuration of the dts generator.

**Comment by TingluoHuang** [comment]
We fixed this recently. Pull master and try it now. :)

**Comment by bryanmacfarlane** [comment]
reopen if it's still an issue.  Ting suggested it's fixed
