### ISSUE TITLE
Debug method being called from getInput in Task.ts in vsts-task-lib

### ISSUE THREAD

**Issue by hiyadav** [Microsoft/vsts-task-lib#127]
I am taking an inline script as an input in AzureCLI Task, and the inline script is being shown in the console, which is not required. 
The method "getInput" in task.ts in vsts-task-lib calls the function "debug" which calls further more function and the input line is printed to the console after string.trim done in "getInput" method. Because of this, inline script input is shown in the console ( the first line of the script is never printed). 
thus it happens when the inline script is greater than one line.

do we really need to print the values we get through getInput ??? can we avoid printing the input values to the console ?

**Comment by bryanmacfarlane** [comment]
Yes - we absolutely need it.  It only prints if system.debug = true which is not the default 

Before we did this, every script littered their tasks with debug statement but inconsistently between tasks

Free debug tracing and consistent debug for troubleshooting is a key principle of both libs

**Comment by hiyadav** [comment]
the system.debug variable in the variables tab in build definition is set to false. and as soon as the input string exceeds one line, the rest of the input for that particular variable(inlineString) is printed to the console. 
@bryanmacfarlane 
![image](https://cloud.githubusercontent.com/assets/20859325/18089425/8cf0a300-6edd-11e6-801e-6bc76c5183a6.png)
