### ISSUE TITLE
Get-VstsVssCredentials fails reporting Required: 'SystemVssConnection' service endpoint URL

### ISSUE THREAD

**Issue by cpaton** [Microsoft/vsts-task-lib#147]
Hi 

I am using v0.7.1 of the vststasksdk PowerShell module in an on-prem TFS 2015 Update 2 installation.  The `Get-VstsVssCredentials` cmdlet is failing reporting

> Required: 'SystemVssConnection' service endpoint URL

From looking at the code it appears the module is expecting ENDPOINT_\* environment variables to be set but they aren't.  Is this expected to work with the on-prem version of TFS or is this module incompatible with update 2?

Thanks

**Comment by ericsciple** [comment]
`Initialize-Inputs` yanks it out of the env var. you can edit the file on disk and add tracing to see if it was there to begin with. i think it should be

**Comment by cpaton** [comment]
Sorry should have added that before.  I have printed out all of the environment variables in my script before importing the VSTSTaskSDK module and there aren't any entries starting with ENDPOINT_, INPUT_ or SECRET_.  This what lead me to think that maybe there is some incompatibility with the version of TFS/VSO agent we have and this module.

**Comment by ericsciple** [comment]
the agent loads the lib before invoking your script

**Comment by ericsciple** [comment]
accidentally closed

**Comment by cpaton** [comment]
After looking around I think this is related to the agent version.  Our TFS installation provides the closed source v1.9.5 agent, I guess this module is designed to work with the [v2 open sourced agent](https://github.com/Microsoft/vsts-agent).  Is that correct?

The [handlers](https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/Handlers/Handler.cs) which run the build steps in the new agent set up the ENDPOINT_ environment variables, but the older agent doesn't do the same.

Checking the [release notes](https://www.visualstudio.com/news/releasenotes/tfs2015-update3-vs) for update 3 of TFS on-premise (latest version available I think) there is no mention of an updated agent.  Do you know if there is an on-prem version that uses/supports the new v2 agent?

**Comment by ericsciple** [comment]
The module works with a 1.95+ agent and you can access the endpoints too, with the exception of the `Data` property (change in handler in 1.97).

Can you confirm whether you calling `Import-Module VstsTaskSdk`? If so, don't do that. It's already loaded before your script is invoked. You can edit the `Initialize-Inputs` function within the module scripts to add tracing and confirm whether the endpoints are present when the module is loaded (look in InputFunctions.ps1). The during initialization (before your script is invoked), the input and endpoint environment variables are removed. The values are stored as secure strings in a hashtable that is a private module-scoped variable.

The 2x agent is for TFS 2016+. RC2 was just released and is go-live. The 2x agent on Windows is not supported with TFS 2015.

**Comment by cpaton** [comment]
Thanks for the information - I am gradually understanding this in more detail.

My PowerShell script is being invoked by a custom build task which uses the `PowerShell` handler.  This is done to be able to import the agent modules and get access to the $distributedTaskContext variable.  For example to import Microsoft.TeamFoundation.DistributedTask.Task.TestResults and publish NUnit results via the PublishResultsCmdlet cmdlet

With this `PowerShell` handler the ENDPOINT_ variables are not setup, to get these variables the `PowerShell3` handler needs to be used.  But using the PowerShell3 handler would not provide access to call PublishResultsCmdlet.  So it would seem it is not easy to use the agent modules and the VSTS task sdk module together.

Suspect using the agent modules from our custom PowerShell scripts is non standard but it allows our build script to be stored in source control along with the code it builds providing some nice flexibility and versioning features.

Think for now I will call the TFS REST API directly from my script and forgo the use of OM helper functions in the VSTS Task SDK PowerShell module.

From having a quick look at the v2 agent code it appears this setup of a PowerShell script stored in source control calling/invoking built in commands like publishing test results is supported natively via emitting correctly formatted log messages.  Is that correct?

**Comment by ericsciple** [comment]
@cpaton sorry i lost track of this issue. yes the [commands emitted over STDOUT](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) can be used to publish test results.

it looks like the `results.publish` command isn't documented for some reason. the commands dont change much, it may be there in older agents as well.
