### ISSUE TITLE
Unable to assert within TaskMockRunner

### ISSUE THREAD

**Issue by colindembovsky** [Microsoft/vsts-task-lib#149]
I have a [task](https://github.com/colindembovsky/cols-agent-tasks/blob/tests/Tasks/ReplaceTokens/replaceTokens.ts) does a regex replace based on tokens in a file (getting values from the variables in the build). To test, I’ve pulled in [mock-fs](https://github.com/tschaub/mock-fs) to fake a file. The problem is that I can’t see a way to validate that the replacement actually happened, either in the test or after the test.

I’ve got a [_testSuite file](https://github.com/colindembovsky/cols-agent-tasks/blob/tests/test/_testsuite.ts) that creates a MockTestRunner to run a test, defined in [test-atTokens.ts](https://github.com/colindembovsky/cols-agent-tasks/blob/tests/test/replaceTokens/test-atTokens.ts). This file in turn creates a mock TaskMockRunner – this is where I create a mock-fs instance to fake the file system (which I register with the TaskMockRunner).

Now after the task completes in the test run, I want to validate the replacement. I tried adding asserts to the test-atTokens file, but even though they fail the test _still passes_. In theory I could check the results in the _testSuite file, but I can’t see how to get a reference the mock-fs instance. So I’m stuck – I can’t see a way to assert from within the TaskMockRunner!

Is there a better way to test this or are there some methods missing in the mock classes for testing tasks?

**Comment by ericsciple** [comment]
sorry for the late response. if you run your test script using [mock-test](https://github.com/Microsoft/vsts-task-lib/commit/27ba0aaeace0c4d33fb4e914db6bfa081c827857), that exposes helper functions that can be used to assert the correct things came back across process boundary via stdout.

**Comment by ericsciple** [comment]
here is an [example](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ShellScript/Tests/L0.ts)

please re-open if needed
