### ISSUE TITLE
XamarinTestCloud Task - Supplying a value for "Optional Arguments" results in a task failure

### ISSUE THREAD

**Issue by DanRigby** [Microsoft/vsts-task-lib#154]
Supplying a value for "Optional Arguments" on the Xamarin Test Cloud task in VSTS results in a build failure with the error message:
`Unhandled: testCloudRunner.argString is not a function`

**Comment by ericsciple** [comment]
@madhurig fyi

**Comment by ericsciple** [comment]
@DanRigby can you open an issue on the [tasks repo](https://github.com/Microsoft/vsts-tasks). This sounds like a bug in the task, not the task lib.

**Comment by DanRigby** [comment]
@ericsciple You're right. I opened this on the wrong repo (I had both open in tabs). Sorry about that.

**Comment by madhurig** [comment]
https://github.com/Microsoft/vsts-tasks/issues/2783
