### ISSUE TITLE
Use powershell commands in script task

### ISSUE THREAD

**Issue by aL3891** [Microsoft/vsts-task-lib#159]
Hello, sorry for the perhaps noobish question but is it possible to use the powershell sdk commands inside a regular script task and not write a complete custom task? 

What I want to do in the end is loop though a parameters.xml file and look up the parameters in there against the running release definition. I've seen that this can be done with environment variables, but that does not include secret variables, something that i'd need for my scenario.

Perhaps there is a different way to do this than using the sdk?

**Comment by ericsciple** [comment]
No. With the current design ad-hoc scripts don't get access to secret variables.

I believe there are a few tasks on the gallery that do token replacement within files.

**Comment by aL3891** [comment]
Allright, thank you for the info :)
I will look and see if I find one and perhaps look at writing a custom one.

**Comment by aL3891** [comment]
I ended up using this Task, I think that's the one you were referring to @ericsciple 
https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens
