### ISSUE TITLE
What is the correct way to debug your scripts in PowerShellOnTargetMachines?

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-task-lib#164]
I have a series of Powershell modules that I am executing with PowerShellOnTargetMachines.

I am trying to see the debug statements within the VSTS build log, but I am having a real hard time getting them to come through.

I understand that Write-Host is not recommended for automation, so my question is, what should I use? I have tried Write-Debug, Write-Verbose and made sure the preferences are set right. But when I call a function from the main script all my logging disappears. The only output I can get to appear is Write-Output from the top most script. I obviously can't use Write-Output from called functions as they may return a value.

This is possibly a more generic powershell question, but I am wondering if there are any best practices for use with this task?

**Comment by ericsciple** [comment]
sorry for the redirection, closing this issue and reopening original issue in vsts-tasks repo https://github.com/Microsoft/vsts-tasks/issues/2983
