### ISSUE TITLE
How to log "Succeeded With Issues" from TypeScript

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-task-lib#176]
In the Powershell SDK there is an option to set the result to `SucceededWithIssues`. I can't find an equivalent option for the Typescript SDK nor can I find documentation whether logging a warning will have this result.

**Comment by ericsciple** [comment]
@jessehouwing error issues and warning issues do not influence task result

**Comment by ericsciple** [comment]
it sounds like the only option currently is to write the [`task.complete` command](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) manually

**Comment by jessehouwing** [comment]
Then i'd like a sdk update to add PartiallySuccessful :)

**Comment by ericsciple** [comment]
in master, will go out w/ the next package (2.0.2-preview). i have some cleanup changes going into that version as well and trying to figure out whether i need one more fix for 2.0.2-preview. should be soon.
