### ISSUE TITLE
mergeResults for CodeCoveragePublisher.publish

### ISSUE THREAD

**Issue by Red-Folder** [Microsoft/vsts-task-lib#186]
Is it possible to provide a mergeResults option for CodeCoveragePublisher.publish (similar the TestPublisher.publish)?

### Use Case
I have a simple Web Application using Asp.Net Core & React

I am using xUnit, OpenCover & OpenCoverToCoberturaConverter to produce a Cobertura coverage report for the Asp.Net code.

I am using Jest to produce a Cobertura coverage report for React.

I can publish both (using separate build steps) to VSTS, but the Code Coverage widget are only based on one of the reports.

I would like VSTS to display Code Coverage for the combined results

**Comment by ericsciple** [comment]
@nigurr do you know about the status of these commands? are these still used by the in-the-box tasks or are the agent `##` commands used now instead?

**Comment by nigurr** [comment]
@ericsciple publishing is still an agent command similar to test reports. 

@Red-Folder currently we don't have plans for this.
