### ISSUE TITLE
Get-VstsEndpoint returning masked credentials

### ISSUE THREAD

**Issue by dotnetnate** [Microsoft/vsts-task-lib#187]
I'm not sure if this intended behavior, but I need to be able to read the credentials from the endpoint information and have had little luck doing so.

I'm making the following call (I've attempted w/ and w/o -Require) 
`$endpoint = Get-VstsEndpoint $ConnectedServiceName `

and when serializing to JSON, it yields:

`auth: {"parameters":{"username":"********","password":"********"},"scheme":"UsernamePassword"}`

and both the username and password properties are reporting as System.String. 

I was initially using this with a custom service endpoint and auth scheme, removed those out of the equation and went to Generic, still the same behavior.

Is this expected or is there a way to correct this? I'm assuming there is given that I've seen examples of people making the call, presumably successfully.

**Comment by bryanmacfarlane** [comment]
That is not how it gets deserialized.  It doesn't yield that.

You are logging the json.  It's the log that's masking the secret.

**Comment by dotnetnate** [comment]
That's not the only way it was verified. I have a user name and password variable, which are originally assigned from task inputs. Everything works correctly when that takes place. If I assign the contents of username/password from the endpoint to those variables the connection fails. Moreover, calling Write-Host on each variable with the input assignment shows the expected contents in the lof, whereas when re-assigning from the endpoint, it doesn't. If it was securestring this would arguably make sense, but as it's not, it doesn't.

**Comment by ericsciple** [comment]
auth.parameters is a string->string dictionary

dumping the endpoint to a file may help illuminate what is going on. when using convertto-json, you may need to specify a higher depth, e.g. `-depth 99`.

the secrets in the output logs are scrubbed by the logger - i.e. replaced with "********"
