### ISSUE TITLE
Values are 'undefined' for variable names with space

### ISSUE THREAD

**Issue by vincentdass** [Microsoft/vsts-task-lib#189]
Values are undefined for variable name with space.
![image](https://cloud.githubusercontent.com/assets/20121508/21378917/108c33a6-c770-11e6-8490-b201949547b4.png)
During task execution, tl.getVariable('system debug true') or tl.getVariables(); provides 'undefined' as variable value.
![image](https://cloud.githubusercontent.com/assets/20121508/21378965/68706150-c770-11e6-8069-e10a4a82af0c.png)

**Comment by ericsciple** [comment]
i think you're on an older version of the lib. this is fixed in master: https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L352

although i'm not sure which release it was fixed in. it doesnt seem to be documented in the release notes.
