### ISSUE TITLE
tl.which finds shell script before `.cmd`

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-task-lib#190]
When trying to find an executable on Windows, tl.which will find the extensionless shellscript version before finding the matching `.cmd`. When calling into Node this requires us to always add:

```
if (tl.osType == "Windows_NT")
{
        tool += ".cmd";
}
```

which is pretty useless... extensionless files can't be executed by default... Windows always searches in a fixed order. Is there any way to have tl.which prefer `tool.cmd` over `tool.`?

Wouldn't it make sense if it would respect the `pathext` variable?

```
C:\>echo %pathext%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```

**Comment by ericsciple** [comment]
yes on windows it should match windows. i think it's fixed in a later shelljs which we were planning to move to, but there are subtle differences in other shelljs functions we consume in the newer versions.

**Comment by ericsciple** [comment]
it would be good to change this in 2.x before removing preview

**Comment by ericsciple** [comment]
PR: https://github.com/Microsoft/vsts-task-lib/pull/231

**Comment by ericsciple** [comment]
in master now, releasing soon.
