### ISSUE TITLE
step-by-step node is no longer working

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-task-lib#191]
To fix replace:
```
$ touch typings.json
$ typings install dt~node --global --save
$ typings install dt~q --global --save
```
with
``` 
npm install @types/node --save-dev
npm install @types/q --save-dev
```

**Comment by igorguga** [comment]
And for people who had done the typings commands (like me), it's necessary to delete typings.json file and typings folder.

**Comment by bryanmacfarlane** [comment]
Thanks.  I'll fix today.

**Comment by BerendWouters** [comment]
I one up this, because this still isn't fixed in the docs.

**Comment by damccorm** [comment]
I'm going to close here since it looks like this is already fixed - https://github.com/Microsoft/vsts-task-lib/blob/9cedd04cc64c6b899b8b7826c54ec67c4682aa28/node/docs/stepbystep.md#add-typings-for-externals
