### ISSUE TITLE
Set-VstsTaskVariable Writes Secret Variable Value to Log

### ISSUE THREAD

**Issue by Gaikotsu2** [Microsoft/vsts-task-lib#194]
When using the following code in my custom task, the value of the Secret variable is written to the logs.
`Set-VstsTaskVariable -Name test_pass -Value <password> -Secret;`

The output is as follows:
`##vso[task.setvariable variable=test_pass;issecret=True]<password>`

I would expect the output to be something like this
`##vso[task.setvariable variable=test_pass;issecret=True]`

This might only happen when using the documentation instructions for Testing and Debugging, I have not tested on our live production system.
(https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/TestingAndDebugging.md)

**Comment by ericsciple** [comment]
the agent scrubs it in memory at runtime before it makes it to the log file

**Comment by waldemarderrennbootlenker** [comment]
When writing some complex string like connectionstring to the outputvariable, the secrets are not allways detected correct. From my point of view the output needs to be reviewed.

**Comment by damccorm** [comment]
Hey @waldemarderrennbootlenker - could you provide an example string that isn't being detected correctly?

**Comment by waldemarderrennbootlenker** [comment]
Hi @damccorm, we are writing an azure storageAccount connectionstring to the variable. So it is something like : 

`DefaultEndpointsProtocol=https;AccountName=mycoolstorageaccount;AccountKey=xxxxxxxxxxxxmysaskeyxxxxxxxxxxxxxxxxxxxx==;EndpointSuffix=core.windows.net`


Output in debug mode then look like this:

2019-12-13T10:33:42.1917738Z ##[debug]Set mySAConString = '********'
2019-12-13T10:33:42.1918717Z ##[debug]Processed: ##vso[task.setvariable variable=mySAConString ;issecret=True]DefaultEndpointsProtocol=https;AccountName=mycoolstorageaccount;AccountKey=xxxxxxxxxxxxmysaskeyxxxxxxxxxxxxxxxxxxxx==;EndpointSuffix=core.windows.net

**Comment by waldemarderrennbootlenker** [comment]
Update: 
Noticed, that the connectionsstring had a "%3B" in its logging command.
When removing the replace of "%3B" from "LoggingCommandFunctions.ps1 from VstsTAskSdk, the string is properly detected as a secret.

**Comment by damccorm** [comment]
This is probably related to https://github.com/microsoft/azure-pipelines-task-lib/issues/589 which I believe @jtpetty was taking a look at. Because of our escaping rules, this variable is getting modified as of #543. @jtpetty we should probably react on the agent side and just be a little more aggressive in what we mask.

**Comment by jtpetty** [comment]
@damccorm - This was fixed in https://github.com/microsoft/azure-pipelines-agent/pull/2659 of the agent and will be included in 2.164.0
