### ISSUE TITLE
Unable to get ServicePrincipal EndpointAuthorization using TypeScript API

### ISSUE THREAD

**Issue by mclark1129** [Microsoft/vsts-task-lib#196]
I may just be missing something obvious in the documentation, but I cannot seem to get the unprotected values for endpoint authorization using the TS API.  I am using the `ServicePrincipal` auth scheme and I would like to use the `serviceprincipalid`, `serviceprincipalkey` and `tenantid` in order to request an OAuth token from Azure AD.  However, the only values I can seem to get from the dictionary are `*****`.  As a result, I'm getting a 404 when trying to build out the Oauth URL.

E.g.

`var clientId = tl.getEndpointAuthorization(connectedServiceName, 'serviceprincipalid', true);`

`clientId` is `******` in when writing to the console with `console.log`.  I thought maybe it was just a feature of the task runtime to protect sensitive data but when I build the URL:

`var tokenHost = "https://login.microsoftonline.com/" + tenantId;`
it resolves to `https://login.microsoftonline.com/*****`.  Again I might jus tnot be working with the API correctly, but I don't see anything else in the documentation regarding sensitive values.

**Comment by ericsciple** [comment]
the logger scrubs secrets. it's just a UI thing. you can dump the value to a file to verify.
