### ISSUE TITLE
Powershell Hashtables no longer work when using SDK

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/vsts-task-lib#198]
I have a build task written in Powershell that uses the Hashtable feature from PS to pass data between functions. All the data is within the task itself. If I don't pull in the SDK but stick with PS proper then everything works. When I bring I the SDK then at runtime PS reports an error saying "Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Collections.Hashtable".

The only thing that differs between the working and non-working versions is the inclusion of the SDK. I don't understand how the SDK is getting in the way.  The relevant pieces of the script.

`function GenerateAttributes 
{
   $attributes = @{
      "Key1" = "value1";
      "Key2" = "value2";
   }
   return $attributes;
}

function UpdateStuff 
{
   param(
       [hashtable] $attributes
   )
}

$attributes = GenerateAttributes
UpdateStuff $attributes
`

**Comment by ericsciple** [comment]
I am unable to repro. I'm on PSVersion 5.1.14393.693

Here is my task script:
```powershell
function GenerateAttributes {
    $attributes = @{
        "Key1" = "value1";
        "Key2" = "value2";
    }
    return $attributes;
}

function UpdateStuff {
    param([hashtable] $attributes)
    Write-Host ("attributes.GetType().Name: " + $attributes.GetType().Name)
    Write-Host ("attributes.Keys.Count: " + $attributes.Keys.Count)
    Write-Host ("attributes['Key1']: " + $attributes['Key1'])
    Write-Host ("attributes['Key2']: " + $attributes['Key2'])
}

$attributes = GenerateAttributes
UpdateStuff $attributes
```

Here is the output:
```
attributes.GetType().Name: Hashtable
attributes.Keys.Count: 2
attributes['Key1']: value1
attributes['Key2']: value2
```

Can you clarify whether you are using the "PowerShell3" handler? Also whether you are importing the VstsTaskSdk (should not do that, handler does it before calling your script)?

**Comment by CoolDadTx** [comment]
Yes I'm using Powershell3 handler. I don't have an implicit import for VstsTaskSdk. I replicated this issue on 2 different machines using the same script. In my case I was enumerating the hashtable using a foreach but I believe the call was failing at entry to the function. Michael Taylor - Microsoft MVP, MCAD
http://www.michaeltaylorp3.net 

    On Sunday, February 5, 2017 9:19 AM, ericsciple <notifications@github.com> wrote:
 

 I am unable to repro. I'm on PSVersion 5.1.14393.693Here is my task script:function GenerateAttributes {
    $attributes = @{
        "Key1" = "value1";
        "Key2" = "value2";
    }
    return $attributes;
}

function UpdateStuff {
    param([hashtable] $attributes)
    Write-Host ("attributes.GetType().Name: " + $attributes.GetType().Name)
    Write-Host ("attributes.Keys.Count: " + $attributes.Keys.Count)
    Write-Host ("attributes['Key1']: " + $attributes['Key1'])
    Write-Host ("attributes['Key2']: " + $attributes['Key2'])
}

$attributes = GenerateAttributes
UpdateStuff $attributesHere is the output:attributes.GetType().Name: Hashtable
attributes.Keys.Count: 2
attributes['Key1']: value1
attributes['Key2']: value2
Can you clarify whether you are using the "PowerShell3" handler? Also whether you are importing the VstsTaskSdk (should not do that, handler does it before calling your script)?—

**Comment by ericsciple** [comment]
What version of PowerShell?

> I replicated this issue on 2 different machines using the same script. In my case I was enumerating the hashtable using a foreach but I believe the call was failing at entry to the function.

I'm confused, are you saying you used the exact script I pasted? Or some other other script involving a foreach? Note, the script I pasted was my entry script that task.json points to. If you can send the smallest possible repro to ersciple would be great (at microsoft com).

**Comment by ericsciple** [comment]
..forgot to mention. if you can zip the task folder and send. or might have better luck pasting here rather than fighting outlook attachment filters.

**Comment by CoolDadTx** [comment]
I'm using PS 5.1. I went back to the original extension that I was trying to use hashtables with and switched back to them along with using the newest VSTS SDK. The extension is working now. I'm not sure why it was having issues with the hashtable before. The only thing I changed originally to cause it to fail was start using the VSTS SDK. 
I'll assume my problem is resolved until I can replicate the issue again.
Michael Taylor - Microsoft MVP, MCAD
http://www.michaeltaylorp3.net 

    On Sunday, February 5, 2017 9:55 PM, ericsciple <notifications@github.com> wrote:
 

 What version of PowerShell?
I replicated this issue on 2 different machines using the same script. In my case I was enumerating the hashtable using a foreach but I believe the call was failing at entry to the function.
I'm confused, are you saying you used the exact script I pasted? Or some other other script involving a foreach? Note, the script I pasted was my entry script that task.json points to. If you can send the smallest possible repro to ersciple would be great (at microsoft com).—
