### ISSUE TITLE
String.prototype.endsWith is not compliant with ES6 standard

### ISSUE THREAD

**Issue by ronwang01** [Microsoft/vsts-task-lib#199]
NodeJs has an ES6 endsWith implementation that is very different from the one in extensions.ts.

Having this library with Node will cause some TLS handshaking to fail due as Node expect endsWith to return true when suffix is an empty string. 

`if (!hostSubdomain.endsWith(suffix))`
[https://github.com/nodejs/node/blob/master/lib/tls.js#L136](https://github.com/nodejs/node/blob/master/lib/tls.js#L136)

This is Node implementation. 
[https://github.com/nodejs/node/blob/73ae2d1895c2c0d1d4eeaddd284c58d776d2be87/deps/v8/src/js/string.js#L626](https://github.com/nodejs/node/blob/73ae2d1895c2c0d1d4eeaddd284c58d776d2be87/deps/v8/src/js/string.js#L626)

**Comment by ronwang01** [comment]
I have attempted a fix to unblock node tls handshaking issue. 
#200

**Comment by ericsciple** [comment]
removing in this pr: https://github.com/Microsoft/vsts-task-lib/pull/207

**Comment by ericsciple** [comment]
in master. will go out with 2.0.2-preview
