### ISSUE TITLE
How to access Machine Group tags

### ISSUE THREAD

**Issue by sburgess123** [Microsoft/vsts-task-lib#202]
We use these tags to define server roles that then control which target servers a deployment task is executed on. In the on premise shipped 'WindowsMachineFileCopy' powershell task for example, this tag info is extracted using the cmdlets available through the hosted powershell run by the agent e.g.:

Get-EnvironmentResources -EnvironmentName $fetchedEnvironmentName -TaskContext $distributedTaskContext

Do you know the best way of getting hold of this information in the new decoupled task model?

**Comment by bryanmacfarlane** [comment]
This doesn't seem to be a task lib question or issue.
