### ISSUE TITLE
Documentation for task.cp is wrong.

### ISSUE THREAD

**Issue by ILMTitan** [Microsoft/vsts-task-lib#204]
In, vsts-task-lib/node/docs/vsts-task-lib.md, the documentation for task.cp is a copy of the documentation for task.which.

**Comment by ericsciple** [comment]
this had me worried the doc generation process has a bug, but it looks like the comments are wrong [in the source code](https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L916).

**Comment by ericsciple** [comment]
PR: https://github.com/Microsoft/vsts-task-lib/pull/207

**Comment by ericsciple** [comment]
in master. will go out with 2.0.2-preview
