### ISSUE TITLE
Error running step-by-step node on Windows

### ISSUE THREAD

**Issue by igorguga** [Microsoft/vsts-task-lib#205]
Trying to run the sample in windows and getting this error:

##vso[task.debug]agent.workFolder=undefined
##vso[task.debug]loading inputs and endpoints
##vso[task.debug]loading INPUT_SAMPLESTRING
##vso[task.debug]loaded 1
undefined
##vso[task.debug]Absolute path for pathSegments: C:\ProgramData\Oracle\Java\javapath/echo = C:\ProgramData\Oracle\Java\javapath\echo
##vso[task.debug]Absolute path for pathSegments: C:\Windows\system32/echo = C:\Windows\system32\echo
##vso[task.debug]Absolute path for pathSegments: C:\Windows/echo = C:\Windows\echo
##vso[task.debug]Absolute path for pathSegments: C:\Windows\System32\Wbem/echo = C:\Windows\System32\Wbem\echo
##vso[task.debug]Absolute path for pathSegments: C:\Windows\System32\WindowsPowerShell\v1.0\/echo = C:\Windows\System32\WindowsPowerShell\v1.0\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\/echo = C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\Microsoft SQL Server\110\Tools\Binn\/echo = C:\Program Files\Microsoft SQL Server\110\Tools\Binn\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\Microsoft SQL Server\110\DTS\Binn\/echo = C:\Program Files\Microsoft SQL Server\110\DTS\Binn\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\/echo = C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\/echo = C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\/echo = C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\/echo = C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\Microsoft SQL Server\120\Tools\Binn\/echo = C:\Program Files\Microsoft SQL Server\120\Tools\Binn\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\/echo = C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft Team Foundation Server 2013 Power Tools\Best Practices Analyzer\/echo = C:\Program Files (x86)\Microsoft Team Foundation Server 2013 Power Tools\Best Practices Analyzer\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\Microsoft\Web Platform Installer\/echo = C:\Program Files\Microsoft\Web Platform Installer\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin/echo = C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\/echo = C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\SafeNet\Authentication\SAC\x64/echo = C:\Program Files\SafeNet\Authentication\SAC\x64\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\SafeNet\Authentication\SAC\x32/echo = C:\Program Files\SafeNet\Authentication\SAC\x32\echo
##vso[task.debug]Absolute path for pathSegments: C:\Users\Administrator\.dnx\bin/echo = C:\Users\Administrator\.dnx\bin\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\Microsoft DNX\Dnvm\/echo = C:\Program Files\Microsoft DNX\Dnvm\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\nodejs\/echo = C:\Program Files\nodejs\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\Ant\apache-ant-1.9.6\bin\/echo = C:\Program Files\Ant\apache-ant-1.9.6\bin\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\SourceGear\Common\DiffMerge\/echo = C:\Program Files\SourceGear\Common\DiffMerge\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\Microsoft SQL Server\130\Tools\Binn\/echo = C:\Program Files\Microsoft SQL Server\130\Tools\Binn\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files\Git\cmd/echo = C:\Program Files\Git\cmd\echo
##vso[task.debug]Absolute path for pathSegments: C:\Users\Administrator\.dnx\bin/echo = C:\Users\Administrator\.dnx\bin\echo
##vso[task.debug]Absolute path for pathSegments: C:\Users\Administrator\AppData\Roaming\npm/echo = C:\Users\Administrator\AppData\Roaming\npm\echo
##vso[task.debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft VS Code\bin/echo = C:\Program Files (x86)\Microsoft VS Code\bin\echo
##vso[task.debug]echo=null
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Parameter 'toolPath' cannot be null or empty.
##vso[task.complete result=Failed;]Parameter 'toolPath' cannot be null or empty.

What is the toolPath parameter???

**Comment by ericsciple** [comment]
I'll try and go through this tomorrow. As a go-by, all of the in-the-box tasks [are here](https://github.com/Microsoft/vsts-tasks). Instructions to build the repo is in the readme, so you can see the final layout for each task (under _build dir).

**Comment by digitalmedia34** [comment]
Any ideas? I am getting issues in windows with EXPORT command since it doesnt exists. What would be equivalent be? I tried environment variables but that did not work.

**Comment by rglos** [comment]
@digitalmedia34 environment variables is the fix.

instead of

```
export INPUT_SAMPLESTRING="Hello World"
node index.js
```

use

```
$env:INPUT_SAMPLESTRING = "Hello World"
node index.js
```

This allowed me to successfully [run the task](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/stepbystep.md#run-the-task).

@ericsciple I've not used Mac before, but using VSCode on Windows, to set environment variables in the `Terminal` window, which uses PowerShell, the above example gets it working.

**Comment by digitalmedia34** [comment]
Many thanks @rglos. I'll give that a try
