### ISSUE TITLE
High severity vulnerability found on shelljs@0.3.0

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-task-lib#208]
✗ High severity vulnerability found on shelljs@0.3.0
- desc: Command Injection
- info: https://snyk.io/vuln/npm:shelljs:20140723
- from: vsts-snyk-task@0.0.0 > vsts-task-lib@2.0.1-preview > shelljs@0.3.0
Fix: None available. Consider removing this dependency.

Tested 259 dependencies for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.

**Comment by ericsciple** [comment]
getting closer with this pr: https://github.com/Microsoft/vsts-task-lib/pull/231

**Comment by bryanmacfarlane** [comment]
We don't use shell.exec (the reported vulnerability).
