### ISSUE TITLE
Get-VstsTfsService - workspace.get not working correctly on TFS 2015

### ISSUE THREAD

**Issue by aumanjoa** [Microsoft/vsts-task-lib#209]
Hi Team,

I have written a small powershell task to download specific TFS version control parts:

function Get-SourceControleWorkspace {
    [CmdletBinding()]
    param(
        [string]$tfsLocation,
        [string]$localFolder,
        [string]$agentName,
        [string]$automationChangeset               
        )

    Trace-VstsEnteringInvocation $MyInvocation
    try {

        #important to store the Assemblie in the root of the Task
        $versionControlServer = Get-VstsTfsService -TypeName 'Microsoft.TeamFoundation.VersionControl.Client.VersionControlServer'

        [string]$workspaceName = "Workspace_$($agentName)"

        #get existing workspace if exists
        $workspace = $versionControlServer.QueryWorkspaces(
                     $workspaceName, 
                     $versionControlServer.AuthorizedUser, 
                     $env:computername) | Select -First 1

        if (!$workspace)
        {
            #worksace not existing create one
            Write-Host "Workspace not existing - creating workspace"
            $workspace = $versionControlServer.CreateWorkspace($workspaceName)            
        }

        #mapp the workspace to the correct TFS Folder
        $workingfolder = New-Object Microsoft.TeamFoundation.VersionControl.Client.WorkingFolder($tfsLocation,$localFolder)    
        $workspace.CreateMapping($workingFolder)

        #define rules how to get the workspace
        $recursionType = [Microsoft.TeamFoundation.VersionControl.Client.RecursionType]::Full    
        $getOptions = ([Microsoft.TeamFoundation.VersionControl.Client.GetOptions]::GetAll -BOR [Microsoft.TeamFoundation.VersionControl.Client.GetOptions]::Overwrite)

        if($automationChangeset)
        {
            $changeset = New-Object Microsoft.TeamFoundation.VersionControl.Client.ChangesetVersionSpec($automationChangeset)
        }else{
            $changeset = [Microsoft.TeamFoundation.VersionControl.Client.VersionSpec]::Latest
        }

        Write-Verbose "$($tfsLocation), $($changeset), $($recursionType), $($getOptions)"
        #get Specific Content
        $workspace.Get($tfsLocation,  $changeset, $recursionType, $getOptions)        

    }
    Catch
    {
        $errorMessage = $_.Exception.Message
        Write-VstsTaskError $errorMessage
        throw [System.Exception] "source Controle Get failed"

    } finally {
        Trace-VstsLeavingInvocation $MyInvocation
    }
}

This works great on TFS2017 as well with the changeset. 
On TFS2015 I always get

> 2017-02-17T14:30:57.8856797Z NumFailures            : 0
2017-02-17T14:30:57.8856797Z NumOperations          : 0
2017-02-17T14:30:57.8856797Z NumFiles               : 0
2017-02-17T14:30:57.8856797Z NumBytes               : 0
2017-02-17T14:30:57.8856797Z NumConflicts           : 0
2017-02-17T14:30:57.8856797Z NumResolvedConflicts   : 0
2017-02-17T14:30:57.8856797Z NumUpdated             : 0
2017-02-17T14:30:57.8856797Z NumWarnings            : 0
2017-02-17T14:30:57.8856797Z NoActionNeeded         : True
2017-02-17T14:30:57.8856797Z HaveResolvableWarnings : False

I am using the .dll´s from the TFS2017 agent

Any idear why this is the case?

sorry the formating is not working correctly

**Comment by ericsciple** [comment]
does the build identity have access to get the sources? https://www.visualstudio.com/en-us/docs/build/troubleshooting#team-foundation-version-control-tfvc
