### ISSUE TITLE
How to package native node dependencies in cross platform extensions

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-task-lib#210]
I'm trying to include `7zip-bin` in an extension. By using `npm install --force` I'm able to force the packaging of all 3 versions (linux, mac and win). The main package then auto-resolves to the right native module for me to use.

But I can't get it to work on the linux agent for a number of reasons:

 * The executables don't get copied to the task folder on the agent
 * I suspect they won't have the required 777 mod flags to allow the executables to work.

The guidance as far as I understand, is to package all dependencies with the task, or use a demand. The first doesn't work. The second doesn't make sense on win32, since the extension satisfies it's own demand by packaging the executable.

I managed to get the task to npm install the right package "on the fly", but that feels very wrong:
```
if (tl.osType() !== "Windows_NT") {
    let postfix = "";
    switch (tl.osType()) {
        case "Linux":
            postfix = "linux";
            break;
        case "Darwin":
            postfix = "mac";
            break;
    }

    tl.cd(__dirname);
    const npmRunner = new tr.ToolRunner(tl.which("npm", true));
    npmRunner.arg("install");
    npmRunner.arg(`7zip-bin-${postfix}`);
    npmRunner.exec();
}

import * as sevenzip from "7zip-bin";
```

See below
```
2017-02-23T19:27:47.9196300Z [command]/usr/local/bin/npm install 7zip-bin-linux
2017-02-23T19:27:50.5833730Z /opt/vsts/work/_tasks/PublishExtension_631511b4-50ab-47c8-b766-7ae2aa672733/100.0.105
2017-02-23T19:27:50.5872720Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
2017-02-23T19:27:50.5910950Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2017-02-23T19:27:50.5941080Z npm WARN 100.0.105 No description
2017-02-23T19:27:50.5960780Z npm WARN 100.0.105 No repository field.
2017-02-23T19:27:50.5987330Z npm WARN 100.0.105 No license field.
2017-02-23T19:27:50.6012710Z `-- 7zip-bin@2.0.4
2017-02-23T19:27:50.6043700Z   `-- 7zip-bin-linux@1.0.3 
```

What's the guidance here. What would be the right way to package native dependencies and still maintain a cross platform build task. Especially now that the hosted agent is there, I'm not really in favor of having people being required to install all kinds of "stuff" on the agent themselves. It should just work".

**Comment by bryanmacfarlane** [comment]
We're starting to tackle some of these same problems here: https://github.com/Microsoft/vsts-task-tool-lib

But more on the extraction side.  It's an interesting question whether we should provide solutions in the task-lib layer which the tool-lib calls.  We're doing a layered tool lib approach since the vast majority of folks aren't writing tool installers.

What are your scenarios?

**Comment by jessehouwing** [comment]
I wanted a single way to handle archives on all platforms. And this seemed a convenient venue not package that handled both the installation, packaging and local resting if the binaries. 

The current limitations got in the way and the archives created by 7z are not being recognized by the vsts marketplace endpoint (complains about a bad zip format).

**Comment by bryanmacfarlane** [comment]
The task should not do npm install at runtime.   it needs to carry whatever it needs to run.
