### ISSUE TITLE
Feature request: Mask string

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-task-lib#216]
I'm trying to integrate the AppInsights Node SDK into a build task to get some feedback from my tasks. 
I want to ensure that I do not accidentally stream secrets from users of my extension to my AppInsights account.

To help me achieve this I need to scrub error messages and traces.

At the moment the Task SDK doesn't have this feature.

**Comment by bryanmacfarlane** [comment]
There isn't - in our model, tasks output logging and it's the agent that holds the secrets and masks them in the logging process.

We could consider adding a lib method for this.  We would have to port that logic to TS.

You can create or morph this into a feature request (enhancement)

**Comment by bryanmacfarlane** [comment]
Closing since the agent does this per above.
