### ISSUE TITLE
Unexpected arguments passed to args.slice when windowsVerbatimArguments flag is set.

### ISSUE THREAD

**Issue by ILMTitan** [Microsoft/vsts-task-lib#218]
If you have a `runTool.cmd` file on the path, and you try to call it like `task.tool('runTool').exec({windowsVerbatimArguments:true})`, the unhelpful error "Unexpected arguments passed to args.slice when windowsVerbatimArguments flag is set." is thrown.

**Comment by ericsciple** [comment]
@ILMTitan can you try `tl.which` and pass full tool path

**Comment by ILMTitan** [comment]
@ericsciple That will work, as does `task.tool('runTool.cmd')...`. `_isCmdFile()` only looks at the extension of the unresolved tool path, which causes this error case to trigger.

**Comment by ericsciple** [comment]
working on something that i think will fix this...

**Comment by ericsciple** [comment]
should be fixed by this PR https://github.com/Microsoft/vsts-task-lib/pull/235
