### ISSUE TITLE
toolrunner failing in Win7 with ENOENT when running a command globally installed with npm-g

### ISSUE THREAD

**Issue by bfcamara** [Microsoft/vsts-task-lib#22]
I am experiencing an issue which I think it is related with this [node issue 2318](https://github.com/nodejs/node-v0.x-archive/issues/2318)

I have a build definition with one step only with the task Npm and configured to do do just `npm --version`. When I run a build in my Win7 I'm getting an error 

`return code: 1`

After some debugging, here is the error that is being bubbled in the promise rejected by the toolrunner

```
C:\Users\bfcamara\AppData\Roaming\npm\npm failed. spawn C:\Users\bfcamara\AppData\Roaming\npm\npm ENOENT
```

Here is what I see in the VSTS console

```
******************************************************************************
Starting task: npm install
******************************************************************************
Set workingFolder to default: E:\Temp\VsoAgent\tasks\Npm\0.2.0
C:\Users\bfcamara\AppData\Roaming\npm\npm install --version
Promise rejected with Error: C:\Users\bfcamara\AppData\Roaming\npm\npm failed. spawn C:\Users\bfcamara\AppData\Roaming\npm\npm ENOENT
return code: 1
******************************************************************************
Finishing task: Npm
******************************************************************************
```

I'm getting this error in any build task that are wrappers for node commands installed globally. From what I could investigate the tl.which("npm") is returning the full path without the extension .cmd. Then it seems there is a known issue in  `child_process.spawn` on windows that it doesn't look for the path with known executable extensions (.cmd, .bat, etc.)

I found this issue while I was doing some tests with a custom build task that is a wrapper for '''tfx extension''' command,

**Comment by TingluoHuang** [comment]
This is a known issue with Shelljs.
https://github.com/shelljs/shelljs/issues/238
modify shelljs code under your node_modules folder like this: https://github.com/shelljs/shelljs/pull/239

**Comment by TingluoHuang** [comment]
In my latest PR for vso-task-lib, i implement Which() on windows platform until Shelljs fix there which().

**Comment by ericsciple** [comment]
it sounds like this was fixed
