### ISSUE TITLE
Get-VstsEndpoint returns null Subscription data from AzureRM Endpoint on TFS2015.3

### ISSUE THREAD

**Issue by hrboyceiii** [Microsoft/vsts-task-lib#221]
First, I appreciate the help on this as it has hit us at an inconvenient time...

We're developing a bunch of tasks that automate Azure ARM deployments.  We migrated to the PowerShell3 handler and VstsTaskSdk over the summer and it has served us well. No issues up until trying to integrate with a high-profile customer on TFS2015.3 (agent version 1.95.3).

We reference VstsAzureHelpers_ from the Vsts-Tasks repo to simplify calling Azure PowerShell scripts.  When our tasks call [Initialize-AzureSubscription](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1#L34) the task fails because "SubscriptionId is null or empty" when executing on Update 3 agent.  This *works* in VSTS hosted agents and our own private agent (v1.105.6) against VSTS.

I've reproduced this by running our scripts using the Invoke-VstsTaskScript and supplying valid values for Endpoint Service Principal and an empty JSON object ("{ }") for Endpoint Data (which *should* be a JSON object with SubscriptionID and SubscriptionName properties).  If I provide a valid Endpoint Data object, the Vsts-Task-Sdk works as expected (on the agent running in a debug PowerShell ISE session).  It does not work when executing/triggered from the TFS Server (i.e. running a release).

I have not found a solution to this nor have any idea on troubleshooting it further.  I've tried updating the Service Endpoint in TFS but that did not work either.  My fear is this is an incompatibility with the PowerShell3 handler and 2015.3.

Again, I sincerely appreciate the help as we're under a time crunch to complete the project by end of the month.  Thank you in advance!!!

**Comment by hrboyceiii** [comment]
Some additional information...Older tasks that were created before VstsAzureHelpers_ and this SDK use Azure PowerShell directly and call the "legacy" Get-ServiceEndpoint commandlet to retrieve endpoint information.  These tasks *work* against TFS 2015.3 -- so I know that the endpoint information is valid.  I hope that helps.

**Comment by ericsciple** [comment]
The [Data property](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/FullHelp/Get-VstsEndpoint.md) requires a 1.97 agent or higher.

**Comment by ericsciple** [comment]
I think the agent version that shipped with TFS 2015.3 was v1.95.x.

**Comment by hrboyceiii** [comment]
@ericsciple Thanks for replying. I guess we missed that in the documentation.  I was told by Premier support that you must use the version of the agent that ships with TFS, so I'm assuming there's no workaround for getting the data property on 1.95.3 -- or using 1.97 with TFS2015.3?

Thanks again for the help.

**Comment by ericsciple** [comment]
For Windows agents on TFS 2015 that is correct.

**Comment by ericsciple** [comment]
Actually I think a newer 1x agent may work (2x Windows agent not supported against TFS 2015). If they don't have many agents, it might be worthwhile to try.

**Comment by ericsciple** [comment]
https://`<account>`.visualstudio.com/_apis/distributedtask/packages/agent?api-version=1

**Comment by hrboyceiii** [comment]
@ericsciple I will talk with the customer; they are in process of migrating a lot of their infrastructure right now and currently still on XAML builds; would we be able to test one machine (2 agents) using this version and leave others at 1.95.3? Risks?

Thanks again.

**Comment by ericsciple** [comment]
Multiple agents can be installed on the same machine. However they should not share the same _work folder.
