### ISSUE TITLE
Accessing ServiceEndPoints from PowerShell

### ISSUE THREAD

**Issue by cpaton** [Microsoft/vsts-task-lib#222]
Our build scripts are stored as PowerShell files within our source repository.  We have written a custom build task that allows us to specify the path to the script to run for a given build definition which uses the PowerShell3 handler.  This works well apart from ServiceEndPoints.  Different builds require access to different end points e.g. one build may need an issue tracker end point and another needs a nuget publication end point.  To be able to access endpoint information from the PowerShell script via VstsTaskSDK we seem to have to add input parameters of type connectedService:Generic to the custom task.  To keep the custom task generic we currently have input parameters called EndPoint1, EndPoint2, ... EndPoint5.

Is there another way to get details of a service end point including authorization information via the VstsTaskSDK module without having to specify input parameters on the task?  The TFS REST API does return information about end points but it doesn't include credential information.

**Comment by ericsciple** [comment]
No not currently. When the build job is constructed (server side), the associated endpoints are added to the job message sent down to the agent. Today there is no just-in-time way to get endpoints.

I'll fwd this along to appropriate folks so they can consider the scenario.

**Comment by ericsciple** [comment]
I've fwd'd the issue along. Closing the issue here since it is a server limitation (feature request) and not an issue with this repo.

**Comment by AbinsC** [comment]
Is there any way to call service endpoint to get some data into Powershell(Build Task)?
