### ISSUE TITLE
Enable importing multiple resource files

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-task-lib#242]
Scenario: common module shared by multiple tasks.

**Comment by bryanmacfarlane** [comment]
I don't get it.  Each common module would have it's own resource file (1) and each task would have it's own resource file (1)

**Comment by ericsciple** [comment]
@stephenmichaelf this would be a good one to knock out. [This PR](https://github.com/Microsoft/vsts-task-lib/pull/252) was never finished but has context about the change.

**Comment by stephenmichaelf** [comment]
Resolved with PR #295.
