### ISSUE TITLE
Debugging- Pass endpoint authorization value through env variables 

### ISSUE THREAD

**Issue by hkamel** [Microsoft/vsts-task-lib#245]
I'm looking for a way to pass the endpoint authorization information to a task through environment variable for debugging purposes.

```
 var myCustomEndpoint = tl.getInput('MyCustomEndPoint', true);
 var myEndpointAuth = tl.getEndpointAuthorization(myCustomEndpoint , false);
```

for the simple endpoint parameters I'm able to use 
$ export MyCustomEndPoint="CustomEndpointName"

Now when getting authorization information, it's always null. how can i pass/mock this value?
```
 var myEndpointAuth = tl.getEndpointAuthorization(myCustomEndpoint , false);
```

**Comment by jessehouwing** [comment]
When you run the build in debug mode `system.debug`=`true`, then the values required by the endpoint are listed in the section where the build initializes. You need a whole number of environment variables. E.g., my VSTS variables tasks lists these parameters when initlializing:

```
loading ENDPOINT_AUTH_e3b134d7-1b55-4d0d-b014-72eb5dc64f94
loading ENDPOINT_AUTH_PARAMETER_e3b134d7-1b55-4d0d-b014-72eb5dc64f94_PASSWORD
loading ENDPOINT_AUTH_SCHEME_e3b134d7-1b55-4d0d-b014-72eb5dc64f94
```

Setting the values for these environment variables prior to running the build should do the trick.

Unfortunately there is no method in the SDK to set these values while testing.

**Comment by hkamel** [comment]
Thanks @jessehouwing. Passing the value directly this way will not work you should pass a JSON string represent the endpoint value like below

`$ export ENDPOINT_AUTH_EP1 = '{ "Parameters": { "UserName": "Some user", "Password": "Some password" }, "Scheme": "Some scheme" }'`

This instruction is well document for the PowerShell task here https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/TestingAndDebugging.md
