### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-task-lib#248]
Hi,

I do see in the PS documentation Invoke-VstsTool cmdlet listed as a part of the SDK. However, if I browse the repo I can't find the source code of it?
Has this been deprecated?

In order to invoke a tool on the build server, what is the best cmdlet to use?

Thanks

**Comment by ericsciple** [comment]
the vsts prefix is added at export time time. it's simply invoke-tool in the source code
