### ISSUE TITLE
Writing Warning and Error messages

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-task-lib#251]
I am building a custom build task that will dialog with our deployment system. At the certain point, in case the deployment fails, I retrieve a message like this from our system:

```
Deployment failed
 
--> Deploy LRDW-DATA-FIX 263137 on environment SDEUC4110424
    --> Deploy LRDW-DATA-FIX 263137 on environment SDEUC4110424
        --> Run RUN_FIX_{{Environment}} on CLOUD_DEV01_SDEUC4110424
 
Log message:
Uploading artifact [C:\windows\temp\ot-20170609T160833790\data-fix]
Copying directory data-fix to working directory.
Uploading file CommandRunner.bat to working directory.
Executing C:\windows\temp\ot-20170609T160833790.1\generic_plugin.tmp\CommandRunner.bat on host Infrastructure/Risk IT/LRDW/CLOUD_DEV01_SDEUC4110424
all good
all good
all good
all good
[ERROR]: Write-Error : A positional parameter cannot be found that accepts argument 
[ERROR]: 'an'.
[ERROR]: At line:1 char:1
[ERROR]: + write-error ooops an error
[ERROR]: + ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]:     + CategoryInfo          : InvalidArgument: (:) [Write-Error], ParameterBin 
[ERROR]:    dingException
[ERROR]:     + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell 
[ERROR]:    .Commands.WriteErrorCommand
[ERROR]: Execution failed with return code 1
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,tmp.ps1
```

The problem is, if I try to use a Write-Error or Write-Warning, the message is not displayed in the build console. In case of Write-Verbose it is all good. Meanwhile if I do Write-Output, half of the message is displayed and an exception is thrown. Is this the expected behavior? How can I display this message in the build console from my custom build task?

Thanks

**Comment by ericsciple** [comment]
what version of TFS? or are you on VSTS? which task execution handler are you using? powershell or powershell3?

**Comment by mmajcica** [comment]
Sorry for missing the info. PS3 handler, TFS 2017.1, Agent 2.112.0.

**Comment by ericsciple** [comment]
In the snippet you pasted, it looks like you may need to add quotes, i.e. `write-error "ooops an error"`

I haven't heard of any issues with Write-Error and Write-Warning not showing up. Any chance the WarningPreference/ErrorPreference is set to something other than Continue/Stop?

Also I'm a bit confused about the issue with Write-Output. Do you have a small repro I can try to illustrate the behavior you are describing?

**Comment by mmajcica** [comment]
Just for completeness,  I'm using SDV version '0.7.1'. I'll prepare you some examples first tomorrow morning as now it is very late at my side. Can you just stick the text I posted in a $variable and try to print it out with a Write-Warning $text  from a task?

Thanks

**Comment by ericsciple** [comment]
Here is my entire powershell3 handler script:
```powershell
$myvar = 'ooops an error'
write-output $myvar
write-warning $myvar
write-error $myvar
write-host $myvar
```

This works as expected for me. Note, the last Write-Host is never called because the error action preference is stop by default. If I add `-ea continue` to the write-error command, then last write-host is output as well.

![image](https://user-images.githubusercontent.com/12102068/27058063-066a70ee-4f9d-11e7-8d10-bb28dcfcf4af.png)

**Comment by mmajcica** [comment]
It works for me also if I do output a single line of text. If the text I'm trying to output is a multi line text as the one I let you the example above, especially if it contains text as Write-Error, it fails to be written. I'll work on an example and post it ASAP.

Thanks

**Comment by mmajcica** [comment]
I found the reason why of this behavior. First, if the variable containing the message to output as a warning, has a New Line character in it, only the chars till the new line char will be shown in build console. Meanwhile if you try to print the same in the PS console, tabs and new line chars are correctly printed out.
I am for now printing it out in the following way:

```
ForEach ($line in $($errorMessaage -split "`r`n"))
{
      if ($line)
      {
            Write-Warning $line
      }
      else
      {
            Write-Output " "
      }
}
```

Also my string contained [char]10 line feed, which I replaced with `"`r`n"`.
This solved all of the issues and now my message is printed out as expected.
I hope this can help to anyone else wondering the same.

**Comment by dvasdekis** [comment]
For those dealing with this issue who find this post, the solution for me was here: https://developercommunity.visualstudio.com/t/failed-powershell-task-write-error-output-is-not-v/344686#T-N1325385

Reprinted for posterity, stick your code inside a try-catch block:

try
{
    # do the work
}
catch
{
    $detailedError = $_
    Write-Host "##vso[task.logissue type=error]$detailedError"
    Write-Host "##vso[task.complete result=Failed;]Script execution failed: $detailedError"
}
The above ensured that the error from the 'work' was reproduced to Github
