### ISSUE TITLE
Unable to find type [Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces.IServiceManager].

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-task-lib#255]
Hello guys, 
Before update TFS 215 to  Tfs 2017 we have used this script [http://blog.jessehouwing.nl/2016/03/access-all-available-build-variables.html](url) Thanks for that, it worked for us very well. 

But with new version of build agent 2.212 stopped working.
> Unable to find type [Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces.IServiceManager].

So, could you please help to resolve this
I`v seen that new agent has the new structure and I found this 
> Microsoft.TeamFoundation.DistributedTask.Task.Legacy SDK.dll
 
Maybe we should use it.

**Comment by ericsciple** [comment]
The powershell3 handler has a function to get all variables.

The powershell handler never supported the feature. The method your are using relies on reflecting over internal types. If you want to continue down that path, I believe the namespace may have changed. The type you are looking for might be named `Microsoft.TeamFoundation.DistributedTask.Agent.LegacyHost.Interfaces.IServiceManager` now. You can use ILSpy to look for the appropriate type in the new DLLs. The DLLs you are looking for are under the `externals\vstshost` directory and `Microsoft.TeamFoundation.DistributedTask.Task.LegacySDK.dll` is probably the DLL you are looking for.
