### ISSUE TITLE
Question: what is the .vsts-ci.yml file used for?

### ISSUE THREAD

**Issue by calebcartwright** [Microsoft/vsts-task-lib#262]
I noticed a [.vsts-ci.yml](https://github.com/Microsoft/vsts-task-lib/blob/master/.vsts-ci.yml) file in this repository, and I am wondering if it does what it seems like (i.e. is to VSTS what a .travis.yml file is to Travis-CI) 

Does the VSTS build (and/or release) system support defining the build in a yaml file in the same repo as the rest of the content? If so is there any documentation on this you could point me to?

**Comment by bryanmacfarlane** [comment]
Yes.  We're self hosting by building this repo using it.  It is getting ready for an early internal preview and we hope to have an early public preview soon.

Here's a link showing our general direction:  https://youtu.be/lkPnv5H2ANI  (that video is a bit old but will give you an idea)

**Comment by calebcartwright** [comment]
Thanks Bryan, that is exciting news!

**Comment by chrisrpatterson** [comment]
@calebcartwright you can find details on getting started https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md
