### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-task-lib#269]
Based on discussions int he internal ALM Champs channels:

It would be lovely if the SDK and the Agent would work together to expose web proxy information that is important for that agent. This allows task developers to correctly pass that information to the tools they execute or set the required environment variables.

My idea would be that it'd be possible to configure a Service Endpoint with the proxy URL and credentials. Then have the ability to set the default proxy endpoint at the agent level in the UI or in the agent when installing it. The VSTS-Task-Lib could then give us access to the endpoint through a well known service endpont (akin to the VSSServiceEndpoint, like VSSProxyEndpoint).

I understand this must go hand-in hand with the agent itself, so I'll post a similar issues in both repositories.

Related VSTS-Task-Lib issue: https://github.com/Microsoft/vsts-agent/issues/1078

**Comment by bryanmacfarlane** [comment]
We already started support in the lib.

https://github.com/Microsoft/vsts-task-lib/pull/268

It's not going to be a service endpoint.  It's configured via agent config as it's an agent concern.

**Comment by bryanmacfarlane** [comment]
Proxy support is complete.  As mentioned above, it's an agent config option.  If you use the task lib, there's methods to get the configured proxy info if you need to pass it on to other tools
