### ISSUE TITLE
Error: Cannot find module 'vsts-task-lib/task'

### ISSUE THREAD

**Issue by Aedalus** [Microsoft/vsts-task-lib#274]
Following the Typescript task documentation, I was able to get a task running locally by calling `node index.js`

However once I've built and published it to my VSTS account, I get the following error when I try to use it in a pipeline:

```
2017-07-20T13:24:34.7853380Z module.js:471
2017-07-20T13:24:34.7867320Z     throw err;
2017-07-20T13:24:34.7883430Z     ^
2017-07-20T13:24:34.7892360Z 
2017-07-20T13:24:34.7910500Z Error: Cannot find module 'vsts-task-lib/task'
2017-07-20T13:24:34.7922580Z     at Function.Module._resolveFilename (module.js:469:15)
2017-07-20T13:24:34.7936460Z     at Function.Module._load (module.js:417:25)
2017-07-20T13:24:34.7951940Z     at Module.require (module.js:497:17)
2017-07-20T13:24:34.7965270Z     at require (internal/module.js:20:19)
2017-07-20T13:24:34.7978890Z     at Object.<anonymous> (/Users/my.agent/myagent/_work/_tasks/DeviceConnectUploadApp_836de0e1-def5-4bc3-ab8b-6a9ee8df6f05/1.0.119/index.js:11:12)
2017-07-20T13:24:34.8009730Z     at Module._compile (module.js:570:32)
2017-07-20T13:24:34.8021870Z     at Object.Module._extensions..js (module.js:579:10)
2017-07-20T13:24:34.8034030Z     at Module.load (module.js:487:32)
2017-07-20T13:24:34.8047560Z     at tryModuleLoad (module.js:446:12)
2017-07-20T13:24:34.8060630Z     at Function.Module._load (module.js:438:3)
```

`vsts-task-lib` is definitely listed as a dependency in my package.json, and I would expect it to be pulled down for the task. Is there anything I need to do to get the build agent to run an npm install for the task?

**Comment by ericsciple** [comment]
you need to publish a self contained task folder. the agent doesnt run npm install to restore your dependencies.

**Comment by Aedalus** [comment]
Ah. I've got it working now, and it makes sense with the way it is designed, but I did find the wording on this step-by-step page a bit ambiguous: https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/stepbystep.md

`Create a .gitignore and add node_modules to it. Your build process should do npm install and typings install. No need to checkin dependencies.`

While I understand now that it is up to MY build process to do the npm install, I took it as like the VSTS build step would do that for me. I don't know if it would be worth trying to make that a bit clearer, or if I just needed more coffee that day.

Thanks for the help!

**Comment by bryanmacfarlane** [comment]
If you want to do a PR to make it clearer that would be great

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by scott-lin** [comment]
I'm encountering this as well.

@Aedalus Do you mind sharing how you fixed this? I'm not sure how to "publish a self contained task folder" as suggested by @ericsciple. It would help if the step-by-step instructions addressed this recurring issue.

**Comment by BrianJayChung** [comment]
> I'm encountering this as well.
> 
> @Aedalus Do you mind sharing how you fixed this? I'm not sure how to "publish a self contained task folder" as suggested by @ericsciple. It would help if the step-by-step instructions addressed this recurring issue.
> 
> The fix I tried was to package the node_modules folder into the root of my vsix. Perhaps it needs to be at another location for my index.js (in a subfolder of the root called src) to find.
> 
> **Edit**: packaging the node_modules side-by-side with the source files fixed the issue. Hope this helps others.

@scott-lin it didn't work for me... Do you mind providing a step by step solution for this?

**Comment by stephenmichaelf** [comment]
@BrianJayChung Did you run npm install so that you have a fully self contained task folder? Can you post a screenshot of the contents of your task folder?

**Comment by BrianJayChung** [comment]
@stephenmichaelf Yeah I ran npm install within my task folder (named Rollout), below is a screenshot of it 
<img width="513" alt="Screen Shot 2019-04-16 at 10 40 51 AM" src="https://user-images.githubusercontent.com/17419302/56231852-485b0000-6034-11e9-9d48-580cfa48a421.png">

**Comment by damccorm** [comment]
@BrianJayChung which version of the task-lib are you using? And what's the exact error you're running into?

**Comment by BrianJayChung** [comment]
@damccorm I am using azure-pipelines-task-lib 2.8.0. The error occurs whenever I run a build task (see below)

`Error: Cannot find module 'azure-pipelines-task-lib/task'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vsts/work/_tasks/Rollout_60714f95-3c8a-4807-a0ca-6253215cf74c/3.0.4/index.js:2:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
##[error]Exit code 1 returned from process: file name '/home/vsts/agents/2.149.2/externals/node/bin/node', arguments '"/home/vsts/work/_tasks/Rollout_60714f95-3c8a-4807-a0ca-6253215cf74c/3.0.4/index.js"'.`

**Comment by BrianJayChung** [comment]
I am using azure-pipelines-task-lib 2.8.0. The error occurs whenever I run a build task (see below)

> Error: Cannot find module 'azure-pipelines-task-lib/task'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/vsts/work/_tasks/Rollout_60714f95-3c8a-4807-a0ca-6253215cf74c/3.0.4/index.js:2:10)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
> ##[error]Exit code 1 returned from process: file name '/home/vsts/agents/2.149.2/externals/node/bin/node', arguments '"/home/vsts/work/_tasks/Rollout_60714f95-3c8a-4807-a0ca-6253215cf74c/3.0.4/index.js"'.

**Comment by BrianJayChung** [comment]
It's working now I'm not sure why .... However, I did validate that npm_modules will need to be in the same directory as the `index.js` file under the task folder.

**Comment by shudv** [comment]
It might be too late, but mentioning this anyway for people who hit this in the future. I just published a [starter template](https://github.com/shudv/azure-pipelines-task-template) for creating custom pipeline tasks in TypeScript. I spent far too much time in setting this up for myself so I'd be happy if it saves some time for people who hit this in the future.

**Comment by Mykyta** [comment]
Hi guys, I've faced with the same error. But to reduce the extension package size, I point the path to lib in manifest file, such as 
```
 {"path": "nexusIQ/node_modules/azure-pipelines-task-lib"},
 {"path": "nexusIQ/node_modules/balanced-match"},
{"path": "nexusIQ/node_modules/brace-expansion"},
{"path": "nexusIQ/node_modules/concat-map"},
 {"path": "nexusIQ/node_modules/minimatch"},
 {"path": "nexusIQ/node_modules/mockery"},
{"path": "nexusIQ/node_modules/q"},
{"path": "nexusIQ/node_modules/semver"},
 {"path": "nexusIQ/node_modules/shelljs"},
{"path": "nexusIQ/node_modules/uuid"}
```
with whole dependencies. Maybe some resolve that issue?
