### ISSUE TITLE
Typescript task lib incompatible with @types/node 8.0.23 

### ISSUE THREAD

**Issue by sandorfr** [Microsoft/vsts-task-lib#278]
The task lib breaks with most recent node typings with such kind of error:
```
Tasks/XmlPatch/node_modules/vsts-task-lib/mock-task.d.ts(14,22): error TS2420: Class 'FsStats' incorrectly implements interface 'Stats'.
```

Reverting to `@types/node` `8.0.19` solves the build error.

**Comment by bryanmacfarlane** [comment]
The agent uses node 6.x to run tasks.

**Comment by sandorfr** [comment]
That makes a lot of sense. Sorry and thank you :)

**Comment by grayjeremy** [comment]
I'm getting this error in mock-task.d.ts as well, seems to have been introducted in the node typings https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e792d401de807aacdedb14fbc06677347c903602  / https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18917

The typescript error I get from vsts-task-lib is

> [ts]
Class 'FsStats' incorrectly implements class 'Stats'. Did you mean to extend 'Stats' and inherit its members as a subclass?
  Property 'atimeMs' is missing in type 'FsStats'.

When I add the following directly to mock-task.d.js, everything compiles     
 ```
    atimeMs: number;
    mtimeMs: number;
    ctimeMs: number;
    birthtimeMs: number;
```

I'd do a PR, but I don't know how the typings file is getting created.  It seems like the 4 fields need to be added [here](https://github.com/Microsoft/vsts-task-lib/blob/master/node/mock-task.ts#L110) and to the typings.
