### ISSUE TITLE
findMatch type definition file generates error when strictNullChecks is enabled

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/vsts-task-lib#282]
I'm new to writing VSTS tasks with typescript but I've used TS in web apps. I might be missing something here but I'm using findMatch to find some files. Using the MSbuild task as an example I'm passing null as the defaultRoot parameter. Based upon the documentation it'll default if you pass null so that is what I'm doing. But with strictNullChecks turned on it reports an error because null cannot be converted to string. I'm guessing the function parameter needs to be changed to indicate it is optional?

**Comment by stephenmichaelf** [comment]
@CoolDadTx Could you use an empty string like [this](https://github.com/Microsoft/vsts-task-lib/blob/4dd8ef3a52cd3e25fab3fbb8d9cb20728fd191ba/node/test/findmatchtests.ts#L42)?

**Comment by CoolDadTx** [comment]
I moved on from this project so I cannot answer whether it would resolve my issue or not.

**Comment by bryanmacfarlane** [comment]
OK.  Closing.
