### ISSUE TITLE
NPM install results in 'File [...] does not have an extension, and its content-type is not declared. Defaulting to application/octet-stream.'

### ISSUE THREAD

**Issue by Aedalus** [Microsoft/vsts-task-lib#283]
I'm trying to create a CI/CD pipeline for my vsts extensions, but I'm having a problem when trying to do npm installs. The install itself will work fine, but when the Package Extension task runs, I get a lot of warnings like:

`File d:\a\1\s\DevOpsScriptsAndTools\VSTSExtensions\DevOpsKatanas\device-connect-upload-app\node_modules\.bin\semver does not have an extension, and its content-type is not declared. Defaulting to application/octet-stream.`

This does not cause the package extension task to fail though. However when I run the Publish Extension task, that fails with a 

`error: Validation timed out. There may be a problem validating your extension. Please try again later.
2017-08-28T18:37:50.2015016Z 
##[error]tfx failed with error: Error: d:\a\_tools\tfx.cmd failed with return code: 4294967295`

If I disable my npm install, it will not throw the warning and publish without issue. However then my tasks won't run properly as they are missing dependencies.

Any help would be much appreciated!

**Comment by bryanmacfarlane** [comment]
Which task in this repo are you having an issue with?  It seems like you are struggling with npm and tfx and not a specific task in this repo

**Comment by Aedalus** [comment]
Thanks for the response!

Perhaps this was the wrong place to post my issue then. I was just following the guide in this repo for getting a node task deployed, and trying to set up a CI/CD pipeline for it. If the Publish Extension VSTS task is failing, I'll try to find the appropriate forum for it.

Thank you,
Alex

**Comment by bryanmacfarlane** [comment]
look here: https://github.com/Microsoft/tfs-cli
