### ISSUE TITLE
Question: Which "VSTS Task SDK" version is correct for our BuildTasks? 

### ISSUE THREAD

**Issue by alexiffland** [Microsoft/vsts-task-lib#286]
Hello, i have a few questions regarding the custom buildsteps of our company:

- What is the correct procedure of adding the SDK to our buildsteps? 
- How can we ensure that BuildTasks using a specific version of the SDK are still working with future Build Agents? 
- Is the SDK backwards-compatible, so we can create our tasks and always add the newest version of the SDK? 

Thanks.

**Comment by ericsciple** [comment]
Yes, use the latested lib.

The agent is backward compatible. Builds that are working should not suddenly stop working due to an agent update.

Note, [some features](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/minagent.md) are not available in older agents.
