### ISSUE TITLE
Is there a way to define custom properties in task.json and consume those in the build task?

### ISSUE THREAD

**Issue by ppejovic** [Microsoft/vsts-task-lib#287]
Is there a way to define a static custom property in `task.json` and consume that in the associated (PowerShell) build task? This would not be a user editable input.

We have multiple TFS environments and the property of the task only needs to vary between environments. My thought is that at the point the task is uploaded, our deployment process could set the property in `task.json` to the value specific to the environment. Or would you recommend an alternative approach?

Hope this makes sense. Thanks

**Comment by stephenmichaelf** [comment]
Not sure I entirely understand what you're trying to do. The task is uploaded as an internal process to VSTS. If something needs to vary by environment can you use the build variables? Which task are you looking at? Some more context/details would help. Thanks!

**Comment by damccorm** [comment]
@ppejovic any update on this? Did you find a solution to this/if not could you provide more details?

**Comment by ppejovic** [comment]
@damccorm I ended up writing a separate config.json file which is read by the build step, The values in the config.json are modified by our deployment process that packages up the build step and pushes it to our TFS instances.

**Comment by damccorm** [comment]
Ah, gotcha, that makes sense. Glad you got it to work, I'm going to close here - feel free to reopen if you have any additional thoughts/questions.

**Comment by ppejovic** [comment]
Well I think having it defined in the task.json would be nicer, either in its own config/options section or as an input with a default value that isn’t editable / hidden
