### ISSUE TITLE
Search folder parameter overrides Test Assemblies parameter

### ISSUE THREAD

**Issue by Bogatinov** [Microsoft/vsts-task-lib#288]
### Problem
We have been using VsTest v2 for a while now, and [only recently did **Search folder** became required](https://developercommunity.visualstudio.com/storage/temp/15512-91a9490cafcd8da13dd53191bb01652f.png). We only used **Test assemblies** to find the test projects.

So we added the **Search folder**, but somehow it overrides the **Test assemblies** parameter. 

### Steps to reproduce
I tried on a demo project with few console libraries, separated per [Boundary context](https://martinfowler.com/bliki/BoundedContext.html) as 

```
  FirstBoundary
        IntegrationTests (FirstBoundary.IntegrationTests)
        UnitTests (FirstBoundary.UnitTests)
        App
  SecondBoundary
        IntegrationTests
        UnitTests
        App
   UI
        MVC
        WebAPI
```

### Results
Here are the logs from VSO with [my setup in VsTest v2](https://developercommunity.visualstudio.com/storage/temp/15747-9e8733222c63bbad2e329fa2c3608359.png)
[WithoutSearchFolder.txt](https://github.com/Microsoft/vsts-task-lib/files/1427381/WithoutSearchFolder.txt)
[WithSearchFolder.txt](https://github.com/Microsoft/vsts-task-lib/files/1427382/WithSearchFolder.txt)

As you can see in the logs, it tries to access 

- MVC project which is on the same level in the solution structure and tries to access DLLs which are not specified in **Test assemblies**
- Integration tests instead of specific kind of tests

even though I placed **Test assemblies** parameter.

### When it broke?
The related code in question is https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L1354. As I see that code has not been changed 8 months (when it worked) and it also works by going inside the folder and looking the patterns inside. 
I don't have any system variables, the patterns work without _defaultRoot_, but somehow are overridden with **Search folder** parameter.

So maybe the issue lies in how VSO calls that function. For instance, it may not bind `patterns` correctly which defaults to empty array from 
```
patterns = patterns || [];
```

### Solution

- As [Nitin Gurram](https://developercommunity.visualstudio.com/users/3781/d70fea88-2591-433f-a097-8e99f06990f5.html) has suggested, we can merge those two variables into one and use it as previously with regex. Don't know which request asked for `Search folder` functionality
- Make `Search folder` in VSO optional so that we can update the tasks without breaking our setups
- Make `Search folder` work by using the regex in **Test Assemblies** parameter

_Originally posted on https://developercommunity.visualstudio.com/content/problem/125510/search-folder-field-in-visual-studio-test-task-inc.html_

**Comment by nigurr** [comment]
@ericsciple Any thoughts on this? :)

**Comment by Bogatinov** [comment]
Weird, by adding "$(System.DefaultWorkingDirectory)" it does not work. But by removing the VsTest v2 task, re-adding it with "$(System.DefaultWorkingDirectory)", it finds the tests correctly in a Boundary context defined solution structure.

I fixed the problem, it works as it should. Maybe caching was the problem?

Thanks @nigurr for sticking around and being helpful :)
