### ISSUE TITLE
Updating a ReleaseName

### ISSUE THREAD

**Issue by alexdegroot** [Microsoft/vsts-task-lib#289]
I'm trying to update my Release-name based on a version I read from my artifact folder. In this way I can visually relate the artifact number to the release.
When I on incident used the Build-update step, it did update the associated build:
Write-Host "##vso[build.updatebuildnumber]$($Env:BUILD_BUILDNUMBER)-($version)"
Is this expected behavior?

Most important, how do I update my Releasename, as this doesn't seem to work:
Write-Host "##vso[release.updatereleasenumber]$version"

Thank you!

**Comment by bryanmacfarlane** [comment]
Can you create an issue in the vsts-agent repo?  It handles ## commands
