### ISSUE TITLE
How to mock tl.getEndpointDataParameter and getEndpointAuthorizationParameter?

### ISSUE THREAD

**Issue by damadei** [Microsoft/vsts-task-lib#291]
Hi guys,

How can I mock in a test a call to tl.getEndpointDataParameter or getEndpointAuthorizationParameter?

Thanks,
Daniel

**Comment by fszlin** [comment]
Try setting the env variables:
```
process.env[`ENDPOINT_AUTH_PARAMETER_${endpointId}_${authKey.toUpperCase()}`] = authVal;
process.env[`ENDPOINT_DATA_${endpointId}_${dataKey.toUpperCase()}`] = dataVal;
```

**Comment by johndowns** [comment]
@fszlin Thanks for your help here. I'm also trying to mock the responses to these calls. I've tried using the environment variable names you suggested but I'm still getting an `Endpoint auth data not present` error. Do you have any examples of how you've used this in the past?

In my case I'm trying to test an Azure RM service connection, but I don't know what @damadei is trying to test.

**Comment by bryanmacfarlane** [comment]
@fszlin is correct.  that does mock it including the response.  When you call the tl.getEndpointXXX methods, it reads those environment variables.  So you're injecting data by setting the envvars.

What happens in the non mock real world case is the user selects the endpoint instance.  When the server sends the job to the agent, it includes the end point data.  The task worker process sets those environment variables (same as inputs), then invokes your script out of proc.  So the lib is think wrappers over envvars and stdout.

**Comment by johndowns** [comment]
@bryanmacfarlane thanks for your help. I've now managed to get this working with the `TaskMockRunner`. Here's the sample code I've used in case anyone else has the same issue in future:

```typescript
var endpointId = 'armService';
tmr.setInput('armService', 'armService');
process.env[`ENDPOINT_AUTH_PARAMETER_${endpointId}_SERVICEPRINCIPALID`] = "00000000-0000-0000-0000-000000000000";
process.env[`ENDPOINT_AUTH_PARAMETER_${endpointId}_SERVICEPRINCIPALKEY`] = "dummy-key-value";
process.env[`ENDPOINT_AUTH_PARAMETER_${endpointId}_TENANTID`] = "00000000-0000-0000-0000-000000000000";
```

**Comment by damccorm** [comment]
I'm going to close here since the issue seems to be resolved. Feel free to reopen if appropriate.

**Comment by bernienowel** [comment]
Since this is the only place I have found details on how to mock out the service endpoints I'm adding what looks like the new way for this to work.

I am unsure on how it handles the casing for the passed parameters in the json object so those might need to be adjusted for your use cases.

```ts
var endpointId = 'armService';
tmr.setInput(endpointId, endpointId);
process.env[`ENDPOINT_AUTH_${endpointId}] = { "parameters":  {
    "serviceprincipalid": "00000000-0000-0000-0000-000000000000",
    "serviceprincipalkey": "dummy-key-value",
    "tenantid": "00000000-0000-0000-0000-000000000000",
    }
}
```

**Comment by anteloe** [comment]
Hi, is there some official documentation on this? I need to mock a generic service and I always get an `Endpoint not present: serviceEndpoint` error.

Here's my code so far:
```ts
const endpointId = "serviceEndpoint"
taskRunner.setInput("serviceEndpoint", endpointId)
process.env[`ENDPOINT_AUTH_PARAMETER_${endpointId}_URL`] = "hello"
process.env[`ENDPOINT_AUTH_PARAMETER_${endpointId}_USERNAME`] = "hello"
process.env[`ENDPOINT_AUTH_PARAMETER_${endpointId}_PASSWORD`] = "world"
```

I also tried
```ts
const endpointId = "serviceEndpoint"
taskRunner.setInput("serviceEndpoint", endpointId)
// @ts-ignore
process.env[`ENDPOINT_AUTH_PARAMETER_${endpointId}`] = {
  "parameters": {
    username: "hello",
    password: "world"
  }
}
```

**Comment by anteloe** [comment]
For those who stumble upon the same situation... I just have inspected the code and found my answer there: [https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/task.ts](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/task.ts)

Be sure to check which functions you call and then just search for those functions in that task.ts file. You will find the actual environment variable names, for each case.

**Comment by ricksbrown** [comment]
While this is old and closed it seems to be the primary search result for this question.

Many of the results above work but they are hooked into the underlying implementation and are therefore brittle.

The "Correct (TM)" way I have discovered is to use [tmr.registerMockExport](https://github.com/microsoft/azure-pipelines-task-lib/blob/ab676de8207ae472532e84765d3c9c5e290cb85b/node/mock-run.ts#L61C23-L61C23).




```JavaScript

function endpointLookup(endpointId, param) {
	const endpoints = {
		serviceEndpoint: {
			'AzureKeyVaultDnsSuffix': 'example.com',
			auth: {
				"parameters":  {
					"serviceprincipalid": "00000000-0000-0000-0000-000000000000",
					"serviceprincipalkey": "dummy-key-value",
					"tenantid": "00000000-0000-0000-0000-000000000000",
				}
			}
		}
	};
	return endpoints[endpointId] ? endpoints[endpointId][param] : null;
}

tmr.registerMockExport('getEndpointDataParameter', endpointLookup);

tmr.registerMockExport('getEndpointAuthorization', function(endpoint) {
	return endpointLookup(endpoint, 'auth');
});

tmr.setInput('endpointId', 'serviceEndpoint');
```
