### ISSUE TITLE
For toolrunner.ToolRunner.arg, whether nested quotes are supported or not

### ISSUE THREAD

**Issue by soulxy** [Microsoft/vsts-task-lib#292]
e.g. [commend] cmd.exe " "a b" && " c d " && e && "f g" "

**Comment by bryanmacfarlane** [comment]
It's the same thing you would do from the command line - you need to escape with back slash

https://github.com/Microsoft/vsts-task-lib/blob/master/node/test/toolrunnertests.ts#L707 

user would enter a single backslash to escape (double is for escaping in javascript.

**Comment by bryanmacfarlane** [comment]
What that means as a task author if you're taking a command line string is just take the string and pass it on.  we will parse it into an argv array correctly.

**Comment by soulxy** [comment]
@bryanmacfarlane 
Really, it is no work in this way (`//"`) .  I need to combine multiple commands into one command,  _the reason for existence of quotation marks is one of commands is directory_.  
`cmd.exe \k ""C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat" && manager -o /outPath  devenv  msvc10.sln /rebuild " `.This is real command.

**Comment by bryanmacfarlane** [comment]
> Really, it is no work in this way (//")

backslash not forward.

Try
```js
import trm = require('vsts-task-lib/toolrunner');

let tr = new trm.ToolRunner('ls');
tr.arg('-k');
tr.arg('C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat" && manager -o /outPath devenv msvc10.sln /rebuild ');
```

which correctly parses:

```
##vso[task.debug]which 'ls'
##vso[task.debug]found: '/bin/ls'
##vso[task.debug]which 'ls'
##vso[task.debug]found: '/bin/ls'
[ '-k',
  'C:Program Files (x86)Microsoft Visual Studio 12.0Common7ToolsVsDevCmd.bat" && manager -o /outPath devenv msvc10.sln /rebuild',
```

Or if you need the double quotes, escape with backslash

```js
import trm = require('vsts-task-lib/toolrunner');

let tr = new trm.ToolRunner('ls');
tr.arg('-k');
tr.arg('\"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat" && manager -o /outPath devenv msvc10.sln /rebuild \"');
tr.line("foo");
```

which outputs:
```
##vso[task.debug]which 'ls'
##vso[task.debug]found: '/bin/ls'
##vso[task.debug]which 'ls'
##vso[task.debug]found: '/bin/ls'
[ '-k',
  '"C:Program Files (x86)Microsoft Visual Studio 12.0Common7ToolsVsDevCmd.bat" && manager -o /outPath devenv msvc10.sln /rebuild "',
```

**Comment by bryanmacfarlane** [comment]
Also make sure you're on the latest task lib (2.1)
