### ISSUE TITLE
Document agent version for TFS 2017 Update 3

### ISSUE THREAD

**Issue by nil4** [Microsoft/vsts-task-lib#293]
TFS 2017 Update 3 is [now available](https://blogs.msdn.microsoft.com/bharry/2017/11/06/team-foundation-server-2017-update-3-available/). 

Please update the [minimum agent versions table](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/minagent.md#agent-version-to-tfs-mapping) to include information about this update.

**Comment by stephenmichaelf** [comment]
Completed by PR referenced above. Thanks!
