### ISSUE TITLE
Question: How can i debug my vsts-task with predefined arguments

### ISSUE THREAD

**Issue by alexiffland** [Microsoft/vsts-task-lib#294]
I want to debug my task with predefined arguments. In the task I use the "Get-VststInput"-cmdlet to get the parameters set from our build definition.
Now, for testing/debugging i call "Invoke-VstsTaskScript -ScriptBlock { [...] }" from the SDK in a Debug.ps1-script but i don't know how to pass arguments to the script block, so the "Get-VstsInput" of the task provides the set values from my Debug.ps1 and i don't have to set values trough the console. How can this be achieved? Thanks.

**Comment by ericsciple** [comment]
you can have your script set the env vars that you would normally [set interactively](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/TestingAndDebugging.md#interactive-testing)
