### ISSUE TITLE
Custom tasks does not appear

### ISSUE THREAD

**Issue by sujitks** [Microsoft/vsts-task-lib#297]
Hi,

I have installed the extension in a VSO account, I can see the extension there but none of the tasks (there are multiple tasks in the extension) are available in the build and release editor to select.

Could you please help?

**Comment by ericsciple** [comment]
Not enough info to investigate. Need account name and details about extension and task.

**Comment by bryanmacfarlane** [comment]
Also not a lib issue.  Create a report at developer community
