### ISSUE TITLE
Not able to get correct proxy details using getHttpProxyConfiguration

### ISSUE THREAD

**Issue by omeshp** [Microsoft/vsts-task-lib#302]
The https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/proxy.md here doesn't return password for the proxy correctly, password is always returned as undefined, I tried it with version 2.1.0

We instead had to fallback to the logic used by vso-node-api (https://github.com/Microsoft/vsts-node-api/blob/master/api/WebApi.ts#L96)

**Comment by bryanmacfarlane** [comment]
Can't repro with password envvar set: https://github.com/Microsoft/vsts-agent/blob/master/docs/start/proxyconfig.md

Missing something?

**Comment by omeshp** [comment]
@bryanmacfarlane I am also not able to reproduce now, we can close this. I will reopen if I get additional details.
