### ISSUE TITLE
Cannot import VstsTaskSdk from ad hoc script

### ISSUE THREAD

**Issue by evolcode** [Microsoft/vsts-task-lib#305]
Hello,

Im running a VSTS task "Azure PowerShell" with the lastest version of PowerShell Running.

Here is the snippet of my code:Import-Module -Name VstsTaskSdk
Trace-VstsEnteringInvocation $MyInvocation

Write-Output "Importing AzureHelpers"
Import-Module $PSScriptRoot\ps_modules\VstsAzureHelpers_
Write-Output  "Initializing Azure Connection"
Initialize-Azure

$billing = Get-VstsInput -Name Billing -Require
$resourceGroupName =  Get-VstsInput -Name Resource

I keep getting an error:

The term 'Trace-VstsEnteringInvocation' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Do I import a module? What am I missing?

**Comment by stephenmichaelf** [comment]
@evolcode could you report this issue to the [vsts-tasks](https://github.com/Microsoft/vsts-tasks/) repo? That is the correct one. I know it can be confusing to know where to report :) Someone there should be able to help you out.

**Comment by ericsciple** [comment]
VstsTaskSdk is for custom task authors, not ad hoc scripts. Which one are you trying to write?
