### ISSUE TITLE
Need help with IBM, Websphere integratation

### ISSUE THREAD

**Issue by xdie** [Microsoft/vsts-task-lib#313]
I have used this extension https://github.com/Microsoft/vsts-ibm-websphere-extension and update vsts-task-lib to the last commit thinking that fixes resolve all problems but is not.
I think arguments with quotes it's broken 

Use Windows 2012
WebSphere 8.5

Any can help me to fix them?
function from vsts.ibm.websphere-extenbsion

LOG
`exec tool: C:\IBM\WebSphere\AppServer\profiles\AppSrv03\bin\wsadmin.bat
arguments:
-username
xx
-password
xx
-host
ccqa
-port
8882
-conntype
SOAP
-lang
jython
-c
AdminApp.install('C:/agent/_work/1/s/dist/ear/ClaimCenter-jndi.ear', '[-appname cc -node CCtestNode -server server1 -cell ROW2K12CC05Node03Cell -contextroot /cc -MapWebModToVH [["ClaimCenter" "cc.war,WEB-INF/web.xml" "default_host"]] ]'); AdminConfig.save(); appManager = AdminControl.queryNames('cell=ROW2K12CC05Node03Cell,node=CCtestNode,type=ApplicationManager,process=server1,*'); AdminControl.invoke(appManager, 'startApplication', 'cc');
C:\Windows\system32\cmd.exe /D /S /C "C:\IBM\WebSphere\AppServer\profiles\AppSrv03\bin\wsadmin.bat -username deployer -password gw -host ccqa -port 8882 -conntype SOAP -lang jython -c "AdminApp.install('C:/agent/_work/1/s/dist/ear/ClaimCenter-jndi.ear', '[-appname cc -node CCtestNode -server server1 -cell ROW2K12CC05Node03Cell -contextroot /cc -MapWebModToVH [[""ClaimCenter"" ""cc.war,WEB-INF/web.xml"" ""default_host""]] ]'); AdminConfig.save(); appManager = AdminControl.queryNames('cell=ROW2K12CC05Node03Cell,node=CCtestNode,type=ApplicationManager,process=server1,*'); AdminControl.invoke(appManager, 'startApplication', 'cc');""
WASX7209I: Connected to process "server1" on node CCtestNode using SOAP connector;  The type of process is: UnManagedProcess
WASX7022E: Problem running command "sys.argv = ['cc.war,WEB-INF/web.xml', 'default_host]]', ']');', 'AdminConfig.save();', 'appManager', '=', 'AdminControl.queryNames('cell=ROW2K12CC05Node03Cell,node=CCtestNode,type=ApplicationManager,process=server1,*');', 'AdminControl.invoke(appManager,', ''startApplication',', ''cc');']" -- exception information: com.ibm.bsf.BSFException: exception from Jython:
Traceback (innermost last):
  (no code object) at line 0
  File "<string>", line 1
	sys.argv = ['cc.war,WEB-INF/web.xml', 'default_host]]', ']');', 'AdminConfig.save();', 'appManager', '=', 'AdminControl.queryNames('cell=ROW2K12CC05Node03Cell,node=CCtestNode,type=ApplicationManager,process=server1,*');', 'AdminControl.invoke(appManager,', ''startApplication',', ''cc');']
	                                                           ^
SyntaxError: invalid syntax
WASX7411W: Ignoring the following provided option: [cc.war,WEB-INF/web.xml, default_host]], ]');, AdminConfig.save();, appManager, =, AdminControl.queryNames('cell=ROW2K12CC05Node03Cell,node=CCtestNode,type=ApplicationManager,process=server1,*');, AdminControl.invoke(appManager,, 'startApplication',, 'cc');]
Traceback (innermost last):
  (no code object) at line 0
  File "<input>", line 2
SyntaxError: Lexical error at line 2, column 0.  Encountered: <EOF> after : ""`

**Comment by stephenmichaelf** [comment]
@xdie Are you sure this is an issue with the vsts-task-lib? Since this is an issue with that specific extension can you open the issue there until it's investigated and narrowed to this lib? Thanks!

**Comment by xdie** [comment]
Sorry Guys, thanks!
