### ISSUE TITLE
findMatch API throws exception, if the pattern matches the broken symlink file

### ISSUE THREAD

**Issue by navin22** [Microsoft/vsts-task-lib#317]
### Repro Steps

Call findMatch API with the pattern that matches the broken symlink file. 

#### Actual : 
As the follow symlinks option is true by default, it tries to find and it then end up throwing exception to the caller. 

#### Expected : 
The API should return the matching files at least. Without throwing the exception.  
And conveying the caller the error message, by callback or some other mechanism. 
Or we can have one more API tryFindMatch which does handle these things without throwing the error.

**Comment by stephenmichaelf** [comment]
@navin22 Can you give a more detailed example to reproduce? Including method params and folder/file structure?

Also, follow sym links defaults to true but you can override to false.

**Comment by navin22** [comment]
@stephenmichaelf We call this API from `PublishTestResults` task. Where we use this to get matching TRX or XML test result files.

1. Create a symlink for XML file in folder A in folder B. 
2. Then delete the file in folder A.
3. then call the `findMatch` API with pattern `B\*.xml`. This will throw an exception.

We want to follow the symlink paths. Hence I am not passing `FindOptions` with false. But if there are some other files matching the pattern in folder B and exists. I want to use those files and give a warning for the files that are missing or broken symlinks.

**Comment by navin22** [comment]
@stephenmichaelf Any update on this?

**Comment by bryanmacfarlane** [comment]
@navin22 - we accept PRs if you want to try and fix ahead of @stephenmichaelf getting to this.  He's on some other higher priority release and OSS tasks.

**Comment by bryanmacfarlane** [comment]
The api is behaving correctly here.  If you want another option, create a PR.  It shouldn't warn as the task author needs to decide whether the option.  Don't pass the warning to the consumer of the task
