### ISSUE TITLE
Non editable endpoint URL should not be cached per endpoint

### ISSUE THREAD

**Issue by henryju** [Microsoft/vsts-task-lib#318]
In our extension we are defining a endpoint where URL is hardcoded and not configurable (isVisible = false). We are only interested by letting the user configure the credentials.

The problem seems to be that the hardcoded URL is attached to endpoint attributes when the endpoint is first created. Later publishing an update of the extension, with the endpoint URL changed, is not propagated to previously defined endpoints. Users have to drop and define again their endpoints, which is tedious.

**Comment by stephenmichaelf** [comment]
@GitHubSriramB Were you able to route this request? Please close once that is done.

**Comment by GitHubSriramB** [comment]
@henryju - Apologies for the delay. We will track this issue & address this limitation in near future.

**Comment by iashishmittal** [comment]
@henryju : 
I agree that if users have to drop and define again their endpoints, it is a tedious process.
But changing URL for existing endpoints directly can have issues. 
As each service endpoint stores their own url information, there can be data inconsistency issue if we start reading URL from extension but remaining data from service endpoint.

We are planning to support updating hidden urls when an endpoint is updated.
During endpoint update, we will check if server url is changed in extension or not. If it is changed then we will update the endpoint url with latest server url.
User will require to give all confidential parameters as that is prerequisite to update any server url in endpoints.

Let me know if you are fine with this behavior change or if there is anything I am missing which is not sufficient to unblock you.

**Comment by henryju** [comment]
A manual action is still required, but at least users will have a way to do it easily. So this is a good enough solution IMO. Thanks for the update.

**Comment by iashishmittal** [comment]
Fix is done in product.
Fix will be deployed in next release cycle which is expected to be in around 5-6 weeks from now.

**Comment by damccorm** [comment]
@henryju I'm going to close since the fix was deployed. Please feel free to reopen if appropriate.

**Comment by henryju** [comment]
Thanks for the notif
