### ISSUE TITLE
Error trying to run git command inside powershell

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/vsts-task-lib#319]
Powershell version: 1.2.3
Agent: Windows 10 pro
Agent version: 2.129.1
Account: precisaosistemas - VSTS
Project: InovaFarma Monitor - Release

Git is installed at the machine, 64bit and 32bit version, also included everything in the path.
The git works fine when I get into the machine and run in powershell, but using VSTS release task it doesn't work.

Error:
```
2018-02-28T18:37:47.4441146Z git : O termo 'git' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a 
2018-02-28T18:37:47.4441839Z grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
2018-02-28T18:37:47.4442209Z No C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\5bce1937-159f-4ee0-837a-3e50c0f8c5aa.ps1:4 caractere:1
2018-02-28T18:37:47.4442409Z + git init "$($env:System_DefaultWorkingDirectory)$($env:GITHUB_FOLDER) ...
2018-02-28T18:37:47.4442551Z + ~~~
2018-02-28T18:37:47.4442694Z     + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
2018-02-28T18:37:47.4442845Z     + FullyQualifiedErrorId : CommandNotFoundException
2018-02-28T18:37:47.4442973Z  
```

Inline script:
```
Param(
 [string]$GH
)
git init "$($env:System_DefaultWorkingDirectory)$($env:GITHUB_FOLDER)" -q
git config core.safecrlf false
git remote add origin https://github.com/$($env:GITHUB_URL).git
git config gc.auto 0
git config --get-all http.https://github.com/$($env:GITHUB_URL).git.extraheader
git config --get-all http.proxy
git -c http.extraheader="AUTHORIZATION: token $GH" fetch --tags --prune --no-recurse-submodules origin --quiet
git pull origin master -q
```

**Comment by stephenmichaelf** [comment]
@marceloavf Which task is this? The issue should probably be created in v[sts-tasks](https://github.com/Microsoft/vsts-tasks/).

**Comment by marceloavf** [comment]
@stephenmichaelf It's [powershell task](https://docs.microsoft.com/pt-br/vsts/build-release/tasks/utility/powershell), should I migrate this issue to vsts-tasks ?

**Comment by bryanmacfarlane** [comment]
The powershell task ran your script.  Is it a problem with the custom script?  Do you believe the powershell task incorrectly ran powershell or are you having problems with your custom script in release.

**Comment by marceloavf** [comment]
@bryanmacfarlane I'm having a problem with powershell running git in this release, I have anothers repositories that run this same script, but in this specific repository this scripts show an output error. 

What I remember for doing diferent from the others is that I imported .json release definition from the other repo, but I already tried to erase this release definition and create from scratch, but the git error is the same.

Powershell is not recognizing git command in this specific repository release.

**Comment by bryanmacfarlane** [comment]
Looks like an issue with the custom script, not powershell or git.

**Comment by marceloavf** [comment]
Strange that it's the same custom scripts in those repositories, but it don't run release in one of them.

**Comment by ericsciple** [comment]
my guess is, you are running the agent as a service account, and git is not in the PATH for that service account

you can confirm by dumping the environment variables

**Comment by bryanmacfarlane** [comment]
In your custom script you can also do a where or which ahead of the command to confirm whether it can be found

**Comment by marceloavf** [comment]
@bryanmacfarlane This `where` or `which` I should use to specify the location of the git command line or bash?

@ericsciple Yes, I'm using agent as a service, also added git in the path and it runs powershell commands, but if that was the problem he would not run others powershell with git command in another repository

**Comment by bryanmacfarlane** [comment]
where (windows) or which (linux or osx) will return where a tool is located according to what's in PATH.

https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line

If it returns empty, then it can't be found in the PATH.  That way you can guard in your script and output it's not in the PATH, please fix.  It also narrows troubleshooting.

**Comment by marceloavf** [comment]
Tried the where command and give this error:
```
2018-03-05T16:16:43.2170835Z ##[error]O termo 'where.exe' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
```

**Comment by stephenmichaelf** [comment]
No .exe

**Comment by marceloavf** [comment]
Empty return, in both agents
