### ISSUE TITLE
Referencing Assemblies from PowerShell and Binding Redirects

### ISSUE THREAD

**Issue by atlastodor** [Microsoft/vsts-task-lib#342]
I am writing a custom build task, where the PowerShell script will need to access additional .Net assemblies. I am having problems referencing those, especially the binding redirects that are normally given in the .config file. 

What is the proper way to handle this? I've seen examples using the ResolveAssembly event, but this to me sounds as a work around. Also, there may be other settings in the .config file that may be relevant and can't be ignored.

PS: Running on TFS 2018 Update 2, on premise.

**Comment by ericsciple** [comment]
.config is for the entry assembly. In this case, powershell.exe is the entry assembly.

Here is [an example](https://github.com/Microsoft/vsts-task-lib/blob/929bc803dc60bd4e56fd83109303e5697d5affee/powershell/VstsTaskSdk/ServerOMFunctions.ps1#L614) where the task lib calls Add-Type to load a DLL.

Here is [an example](https://github.com/Microsoft/vsts-task-lib/blob/929bc803dc60bd4e56fd83109303e5697d5affee/powershell/VstsTaskSdk/ServerOMFunctions.ps1#L433) where a binding redirect is applied, and removed.

Tasks carry a known set of specific dependencies. If other settings need to be accommodated, it is always a known set.

**Comment by atlastodor** [comment]
Thanks Eric. I was aware that .config affects the whole assembly, in this case PowerShell, which if modified will have influence on the whole machine. I was secretly hoping that there was a way to dynamically load a .config file so that only the current process would be affected.

I will look at the resolve assembly examples. This is also what I concluded was probably the way to go. Just a stupid question: What will happen if I explicitly loaded the depending assemblies in the correct version before loading the main assembly? In my case, System.Net.Http 4.1.1.2 instead of the default System.Net.Http 4.0.0.0.

Also, what do you mean by "Tasks carry a known set of specific dependencies"? Do you mean that I as the developer know exactly what the dependencies are?

**Comment by nigurr** [comment]
@atlastodor may be this can help you? https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployVisualStudioTestAgent/DeployTestAgent.ps1#L59

**Comment by atlastodor** [comment]
Hi. This is basically what I do. Except, in the example, I don't see where the on-resolve-assembly handler is hooked.

My code (see below) calls the handler, but only once and only for the Newtonsoft.Json. Not for any other assemblies.

[appdomain]::currentdomain.getassemblies() | sort -property fullname | format-table fullname | Out-String|% {Write-Host $_}

$currentScriptDirectory = Get-Location
$assemblyFolder = Join-Path $currentScriptDirectory "Tfs"
[System.IO.Directory]::SetCurrentDirectory($assemblyFolder)
		
Write-Host "Adding assembly resolver."
$onAssemblyResolve = [System.ResolveEventHandler] {
    param($sender, $e)
    if ($e.Name -like 'Newtonsoft.Json, *') {
        Write-Host "Resolving '$($e.Name)'"
        $assemblyPath = Join-Path $assemblyFolder "Newtonsoft.Json.dll"
        return [System.Reflection.Assembly]::LoadFrom($assemblyPath)
    }
    if ($e.Name -like 'System.Net.Http, *') {
        Write-Host "Resolving '$($e.Name)'"
        $assemblyPath = Join-Path $assemblyFolder "System.Net.Http.dll"
        return [System.Reflection.Assembly]::LoadFrom($assemblyPath)
    }

    Write-Host "Unable to resolve assembly name '$($e.Name)'"
    return $null
}
[System.AppDomain]::CurrentDomain.add_AssemblyResolve($onAssemblyResolve)
	
Add-Type -Path (Join-Path $assemblyFolder "MyLib.dll")
Write-Host "Loaded MyLib"

$service = New-Object MyLib.Service("...", "...")
Write-Host "Service created"

[appdomain]::currentdomain.getassemblies() | sort -property fullname | format-table fullname | Out-String|% {Write-Host $_}
	
# Crashes below with: [A]System.Net.Http.Headers.MediaTypeHeaderValue cannot be cast to [B]System.Net.Http.Headers.MediaTypeHeaderValue.  kk e context 'Default' at location 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Type B originates from 'System.Net.Http, Version=4.1.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'LoadFrom' at location 'C:\TFSAgent-Default-17\_work\_tasks\AtlasGenerateReleaseNotes_130d1a10-3cd0-11e8-81c9-a13fe19f6bca\0.1.42\Tfs\System.Net.Http.dll'.
2018-04-16T07:07:29.4819451Z System.InvalidCastException

$query = $service.Query(1234)

**Comment by nigurr** [comment]
@atlastodor it's handled in the same line as pointed.
   
> $jsonAssembly = [reflection.assembly]::LoadFrom($PSScriptRoot + "\modules\Newtonsoft.Json.dll")
>     $onAssemblyResolve = [System.ResolveEventHandler] {
>         param($sender, $e)
>         if ($e.Name -eq "Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed") { return $jsonAssembly }
>         foreach($a in [System.AppDomain]::CurrentDomain.GetAssemblies())
>         {
>             if($a.FullName -eq $e.Name) { return $a } else { return $null }
>         }
>         return $null
>     }

All you need to do is, instead of `Newtonsoft`, you can change it to `System.Net.Http` assembly properties

**Comment by atlastodor** [comment]
I already have the System.Net.Http in my handler. Only that it is not called. Probably something with the load context for the assembly. I am investigating.

I was asking where the $onAssemblyResolve variable is used. I can't see that this handler is used anywhere.

**Comment by atlastodor** [comment]
After reading the .Net documentation, I came to the conclusion that the AssemblyResolve event is only raised when .Net cannot find the assembly in question.

The problem is that .Net loads the assemblies in the appdomain's default context, and if it can find any assembly that matches the requested assembly, it will be loaded. In my case System.Net.Http, Version=4.1.1.2 is requested but for some reason the system finds System.Net.Http, Version=4.0.0.0 in the GAC and loads that assembly. The event is not raised, since the system found a match. It is only raised if it cannot find the assembly.

I ended up loading an additional AppDomain that is configured to use my custom .config file. This was the simplest approach for me.

**Comment by MiaoXuHui** [comment]
> I already have the System.Net.Http in my handler. Only that it is not called. Probably something with the load context for the assembly. I am investigating.
> 
> I was asking where the $onAssemblyResolve variable is used. I can't see that this handler is used anywhere.

[System.AppDomain]::CurrentDomain.add_AssemblyResolve($OnAssemblyResolve)

**Comment by MiaoXuHui** [comment]
[System.AppDomain]::CurrentDomain.add_AssemblyResolve($OnAssemblyResolve)
