### ISSUE TITLE
VSTS not picking up task update

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-task-lib#349]
I'm not sure if this is the correct repo to ask this question.

I have a few extensions (build/release tasks) on github: https://github.com/gregpakes/vsts.extensions/tree/master/Extensions/CampaignMonitor.  One of my extensions contains two tasks.

One of my tasks will not update despite bumping the version in accordance with the guidelines.  The other task updates fine.

For example:

If I make a change to **CreateCampaignTask** only, I would like to bump the version number for **CreateCampaignTask** and for the extension.  However, if I do this, VSTS does not download the new task.

By contrast, if I make a change to **DeleteCampaignTask** and bump the various version numbers, it works as expected.

> I don't know if it's related, but my extensions use the versioning layout as defined here https://docs.microsoft.com/en-gb/vsts/extend/develop/build-task-schema?view=vsts#bundle-multiple-versions-of-build-tasks-within-one-extension

What am I doing wrong?  This worked fine until I introduced the second task.

**Comment by ericsciple** [comment]
```
A task definition with id '2148d21b-683e-4ca3-b51b-c696c7e326ae' and version '0.0.8' already exists for contribution (gregpakes.campaignmonitor-preview.CampaignMonitor, v0.0.19). An attempt was made to install the same task at version '0.1.0' with contribution (gregpakes.campaignmonitor-preview.CreateCampaignTask, v0.0.20).
```

**Comment by ericsciple** [comment]
1. yes
2. unfortunately it was only in the server errors logs. The error was when the update was attempted on your account. The marketplace is global (it doesnt know about accounts).

**Comment by damccorm** [comment]
@gregpakes it looks like this issue has been resolved so I'm going to close. Feel free to reopen if appropriate.
