### ISSUE TITLE
Example URLs are broken

### ISSUE THREAD

**Issue by MouthOfMadness** [Microsoft/vsts-task-lib#388]
Click the example urls and you get page not found.

**Comment by bryanmacfarlane** [comment]
Can you clarify which urls and which pages?

**Comment by MouthOfMadness** [comment]
The MSBuild Task: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/MSBuild/MSBuild.ps1

The VSBuild Task: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VSBuild/VSBuild.ps1

Under the Reference Example: https://github.com/Microsoft/vsts-task-lib/tree/master/powershell

**Comment by stephenmichaelf** [comment]
Thanks I will fix this.
