### ISSUE TITLE
tasks.schema.json - Is it complete?

### ISSUE THREAD

**Issue by alexmbaker** [Microsoft/vsts-task-lib#392]
Looking at the [VSTS Tasks](https://github.com/Microsoft/vsts-tasks) repository I can see that task.json file for many tasks contains something like

``` json
{
    "visibility": [
		"Build",
		"Release"
	],
}
```
This property is not listed in the tasks.schema.json is this correct?

I have also encountered an additional version property `isTest`, I think it was in the [VSTS REST API](https://docs.microsoft.com/en-us/rest/api/vsts/distributedtask/taskgroups/list?view=vsts-rest-4.1) documentation that I first encountered came across the property.
``` json
{
    "version":  {
                    "Major":  0,
                    "Minor":  1,
                    "Patch":  0,
                    "isTest":  true
                },
}
```
Setting `isTest` to `true` appears to:

1) Show the version number in VSTS as something like  `0.*-test`
2) Allow a release definition to automatically pick the newest version of the task when a new release is created.  I believe that when isTest is not specified then the exact major, minor, patch of the task will be used that was selected when the task was added in to the release definition.  (I assume a similar thing happens with build definitions).  Or perhaps it has something to do with forcing the VSTS Agent to downloading new versions of cached tasks?? 

Some clarification would be helpful.

**Comment by bryanmacfarlane** [comment]
They were intentionally left out because they are not supported / honored completely.  There's a task to go remove it from our tasks.  Sorry for the confusion.

**Comment by damccorm** [comment]
Looks like the isTest property was removed. Visibility is still around, but since its being tracked I'm going to close here. Feel free to reopen as appropriate.
