### ISSUE TITLE
Moving tasks to use latest @types/node throws for mock-task.ts

### ISSUE THREAD

**Issue by prawalagarwal** [Microsoft/vsts-task-lib#396]
As per the requirements on the task owners on Microsoft/vsts-task to move to using [definitely typed type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped), we are moving VsTestPlatformToolInstallerV1 task to use @types/node (v 9.6.31).

Post this the task build fails with:

> node_modules/vsts-task-lib/mock-task.d.ts(14,22): error TS2420: Class 'FsStats' incorrectly implements interface 'Stats'.
  Property 'atimeMs' is missing in type 'FsStats'.

Looks like the mock-task.ts implementation of FsStats needs to implements the new fs.Stats interface.

**Comment by stephenmichaelf** [comment]
We don't support Node 9 right now, can you lower the version for types to 8?

**Comment by bryanmacfarlane** [comment]
tasks are also run with node 6

atimeMs was added in 8.10

stats.atimeMs#
Added in: v8.1.0

Did you try it at runtime?  Seems dangerous

**Comment by prawalagarwal** [comment]
Using 6.0.101 now. The task build fine.
