### ISSUE TITLE
VSBuild and PublishSymbols fail after upgrade to TFS 2015 Update 2 RTM in Japanese locale. 

### ISSUE THREAD

**Issue by MasashiTeruya** [Microsoft/vsts-task-lib#62]
CI build failed in my environment after I upgrade TFS 2015 Update 1 to TFS 2015 Update 2.

logs:
2016-04-02T21:41:21.6214276Z C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; $env:TF_BUILD = 'True' ; Import-Module -Name 'C:\agent\tasks\VSBuild\1.0.24\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\tasks\VSBuild\1.0.24\VSBuild.ps1'''))"
2016-04-02T21:41:29.5855730Z ##[error]':' または '}' ではなく無効なオブジェクトが渡されました。 (473): {
2016-04-02T21:41:29.5855730Z ##[error]  "loc.messages.PSLIB_ContainerPathNotFound0": "繧ｳ繝ｳ繝・リ繝ｼ縺ｮ繝代せ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ: '{0}'",
...
2016-04-02T21:41:29.6793302Z ##[error]  "loc.messages.PSLIB_TaskVariable0": "'{0}' 繧ｿ繧ｹ繧ｯ螟画焚"
2016-04-02T21:41:29.6793302Z ##[error]}

troubleshooting:
The log provided above seems incorrect encoding.
I tried to build ASP.NET and Console App provided default by visual studio and both failed.
TFS App server and Build Agent server are separately installed on 2 hosts.

Versions:
Windows Server 2012 R2 (Locale=ja_jp)
TFS 2015 Update 2 (C:/agent/tasks/VSBuild/1.0.24)
Visual Studio 2015 Update 2

**Comment by MasashiTeruya** [comment]
I quickly tested and found encoding was the problem. ConvertTo-Json cannot parse wrong encoding one.
By default encoding is not UTF8 in Japanese environment...

BAD
> Get-Content -LiteralPath "$env:USERPROFILE\Source\Repos\vsts-task-lib\powershell\VstsTaskSdk\Strings\resources.resjson\ja-jp\resources.resjson"|Out-String|ConvertFrom-Json
ConvertFrom-Json : ':' または '}' ではなく無効なオブジェクトが渡されました。 (473): {
  "loc.messages.PSLIB_ContainerPathNotFound0": "繧ｳ繝ｳ繝・リ繝ｼ縺ｮ繝代せ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ: '{0}'",
  "loc.messages.PSLIB_EndpointAuth0": "'{0}' 繧ｵ繝ｼ繝薙せ 繧ｨ繝ｳ繝峨・繧､繝ｳ繝医・雉・ｼ諠・ｱ",
  "loc.messages.PSLIB_EndpointUrl0": "'{0}' 繧ｵ繝ｼ繝薙せ 繧ｨ繝ｳ繝峨・繧､繝ｳ繝医・ URL",
  "loc.messages.PSLIB_EnumeratingSubdirectoriesFailedForPath0": "繝代せ '{0}' 縺ｮ繧ｵ繝悶ョ繧｣繝ｬ繧ｯ繝医Μ繧貞・謖吶〒縺阪∪縺帙ｓ縺ｧ縺励◆",
  "loc.messages.PSLIB_FileNotFound0": "繝輔ぃ繧､繝ｫ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ: '{0}'",
  "loc.messages.PSLIB_Input0": "'{0}' 蜈･蜉・,
  "loc.messages.PSLIB_InvalidPattern0": "菴ｿ逕ｨ縺ｧ縺阪↑縺・ヱ繧ｿ繝ｼ繝ｳ縺ｧ縺・ '{0}'",
  "loc.messages.PSLIB_LeafPathNotFound0": "繝ｪ繝ｼ繝・繝代せ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ: '{0}'",
  "loc.messages.PSLIB_PathLengthNotReturnedFor0": "繝代せ縺ｮ豁｣隕丞喧/螻暮幕縺ｫ螟ｱ謨励＠縺ｾ縺励◆縲・ernel32 繧ｵ繝悶す繧ｹ繝・Β縺九ｉ繝代せ '{0}' 縺ｮ髟ｷ縺輔′霑斐＆繧後∪縺帙ｓ縺ｧ縺励◆",
  "loc.messages.PSLIB_PathNotFound0": "繝代せ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ: '{0}'",
  "loc.messages.PSLIB_Process0ExitedWithCode1": "繝励Ο繧ｻ繧ｹ '{0}' 縺後さ繝ｼ繝・'{1}' 縺ｧ邨ゆｺ・＠縺ｾ縺励◆縲・,
  "loc.messages.PSLIB_Required0": "蠢・ｦ・ {0}",
  "loc.messages.PSLIB_StringFormatFailed": "譁・ｭ怜・縺ｮ蠖｢蠑上′豁｣縺励￥縺ゅｊ縺ｾ縺帙ｓ縲・,
  "loc.messages.PSLIB_StringResourceKeyNotFound0": "譁・ｭ怜・縺ｮ繝ｪ繧ｽ繝ｼ繧ｹ 繧ｭ繝ｼ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ: '{0}'",
  "loc.messages.PSLIB_TaskVariable0": "'{0}' 繧ｿ繧ｹ繧ｯ螟画焚"
}
発生場所 行:1 文字:156
+ ... esources.resjson\ja-jp\resources.resjson"|Out-String|ConvertFrom-Json
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
GOOD
> Get-Content -LiteralPath "$env:USERPROFILE\Source\Repos\vsts-task-lib\powershell\VstsTaskSdk\Strings\resources.resjson\ja-jp\resources.resjson" -Encoding UTF8|Out-String|ConvertFrom-Json

loc.messages.PSLIB_ContainerPathNotFound0                  : コンテナーのパスが見つかりません: '{0}'
loc.messages.PSLIB_EndpointAuth0                           : '{0}' サービス エンドポイントの資格情報
loc.messages.PSLIB_EndpointUrl0                            : '{0}' サービス エンドポイントの URL
loc.messages.PSLIB_EnumeratingSubdirectoriesFailedForPath0 : パス '{0}' のサブディレクトリを列挙できませんでした
loc.messages.PSLIB_FileNotFound0                           : ファイルが見つかりません: '{0}'
loc.messages.PSLIB_Input0                                  : '{0}' 入力
loc.messages.PSLIB_InvalidPattern0                         : 使用できないパターンです: '{0}'
loc.messages.PSLIB_LeafPathNotFound0                       : リーフ パスが見つかりません: '{0}'
loc.messages.PSLIB_PathLengthNotReturnedFor0               : パスの正規化/展開に失敗しました。Kernel32 サブシステムからパス '{0}' の長さが返されませんでした
loc.messages.PSLIB_PathNotFound0                           : パスが見つかりません: '{0}'
loc.messages.PSLIB_Process0ExitedWithCode1                 : プロセス '{0}' がコード '{1}' で終了しました。
loc.messages.PSLIB_Required0                               : 必要: {0}
loc.messages.PSLIB_StringFormatFailed                      : 文字列の形式が正しくありません。
loc.messages.PSLIB_StringResourceKeyNotFound0              : 文字列のリソース キーが見つかりません: '{0}'
loc.messages.PSLIB_TaskVariable0                           : '{0}' タスク変数


For me, CI build completely works fine now.
In my environment I patched following:
agent\tasks\PublishSymbols\1.0.20\ps_modules\VstsTaskSdk\LocalizationFunctions.ps1
agent\tasks\VSBuild\1.0.24\ps_modules\VstsTaskSdk\LocalizationFunctions.ps1

**Comment by ericsciple** [comment]
I'll get a patched version of the tasks into the releases/m95 branch of the tasks vso-agent-tasks. I'll add some unit tests to prevent regressions if the encoding of the files change.

Thank you for the investigation/fix.

**Comment by ericsciple** [comment]
Also, as a workaround, a variable can be set on the definition: set `system.preferpsoverps3` to `true`.

**Comment by ericsciple** [comment]
Here's the patch: http://go.microsoft.com/fwlink/?LinkId=786947

The zip contains a readme.txt and a ps1 script to upload the patched tasks.

**Comment by ericsciple** [comment]
Fixed in 2.1
