### ISSUE TITLE
Unable to load vsts-task-lib on TFS2015 Update 2 build agent

### ISSUE THREAD

**Issue by gravufo** [Microsoft/vsts-task-lib#66]
Hi,

I'm trying to run an extension in Typescript and it fails with the following error:

`##[debug]load strings from: C:\TFS2015\tasks\BuildNumberGenerator\1.0.19\node_modules\vsts-task-lib\lib.json`

`##[debug]load loc strings from: C:\TFS2015\tasks\BuildNumberGenerator\1.0.19\node_modules\vsts-task-lib\Strings\resources.resjson\en-US\resources.resjson`

`Unhandled: Cannot read property 'match' of undefined`

`##[debug]task result: Failed`

The task is packaged with the node_modules folder in its root containing vsts-task-lib, so I'm not sure what's happening there.

Here are the imports in the code:

```javascript
var tl = require('vsts-task-lib/task');
var webapim = require('vso-node-api/WebApi');
```

Also, is there a way to tell the agent to prefer the powershell version over the node version? It seems to always take the node version when it's available.

Thanks!

**Comment by bryanmacfarlane** [comment]
Tasks package up this lib so it doesn't have anything to do with the server/service version.

https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/vsts-task-lib.md 

For example, our tasks pull down the lib and link it into the tasks at build time.

**Comment by ericsciple** [comment]
You can add a `platforms` section to set handler preference on a specific OS https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/MSBuild/task.json

**Comment by gravufo** [comment]
Thanks @ericsciple that's exactly what I was looking for!

As for the original request, @bryanmacfarlane does not really answer my question/issue. Why is it so difficult to make documentation that **clearly** shows us how to use the lib and package our tasks correctly?

My task has a node_modules that contains the lib when I package it. That package was installed using `npm install --save vsts-task-lib` from the task's root folder. Here's what the structure looks like in vscode: [screenshot](http://puu.sh/omWpX/6911528ad7.png).

There is no .d.ts file packaged with the npm module, so am I supposed to copy it from a manual build? I do have a typings folder, but it's two levels above the task's root, so it's not packaged with it. Here's what my typings folder (at the root of the vscode "project") looks like: [screenshot](http://puu.sh/omWRs/956622159e.png).

Also, do I HAVE to include `/// <reference path="../../typings/main/ambient/vsts-task-lib/index.d.ts" />` even if I already have a reference in my typings/main.d.ts ?

Thanks.
