### ISSUE TITLE
Can this lib be used on TFS 2015 on-prem ?

### ISSUE THREAD

**Issue by LiohAu** [Microsoft/vsts-task-lib#69]
I have just tried to upload a new version of the Xcode task available here : https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/Xcode and I am getting the following error during builds : 

```
module.js:341
throw err;
^
Error: Cannot find module 'vsts-task-lib'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
```

So I guess that the TFS 2015 Update 1 that we are using is probably missing that library. How can I install (update?) it on our TFS server ?
I also noticed that the reference to this library in the vso-agent-tasks repo is not in the package.json but in an externals.json, is there a reason for that ?

I am wondering if all these tasks are only for VSO or if the intended use was VSO or TFS on-prem ?

**Comment by jpricketMSFT** [comment]
All tasks should work on both VSO (Team Services) and TFS on-prem.

Have you installed the .net agent or cross platform agent? The js tasks were designed to run on the cross platform agent. It uses npm to download dependencies. The instructions for installing the cross platform agent can be found here: https://github.com/Microsoft/vso-agent

Thanks,
Jason

**Comment by bryanmacfarlane** [comment]
Correct.

Tasks package up this lib so it doesn't have anything to do with the server/service version.

https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/vsts-task-lib.md 

For example, [our tasks](https://github.com/Microsoft/vso-agent-tasks) pull down the lib and link it into the tasks at build time.

**Comment by ericsciple** [comment]
Generally you shouldn't take a task from the master branch of vso-agent-tasks repo and upload it to your on-premise TFS instance. releases/m89 contains the tasks that shipped with shipped Update 1 and there's no guarantee that taking the task from master will work with your older TFS version. It is not supported.

**Comment by LiohAu** [comment]
I installed the cross platform agent (and the tfx client also).

Then I cloned the vso-agent-tasks repo, and used "tfx build tasks upload ." in the Tasks/Xcode folder.
So basically I have the TFS 2015 Update 1 tasks except the Xcode one which is the last version available.

**Comment by ericsciple** [comment]
Yes. That's not supported.

Aside from that, the reason it can't find the lib is because you didn't build the task. The lib is packaged with the task during the build process.

And the the nodejs lib can be used on Windows agent as well as the cross platform agent.

**Comment by LiohAu** [comment]
@ericsciple shouldn't "tfx build tasks upload ." build the task before uploading (also what does building means for node.js things, is there a sort of compilation?) ?

**Comment by LiohAu** [comment]
When looking at that wiki : https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md it does not show any kind of "building" command it's only "create" and then "upload".

@bryanmacfarlane @jpricketMSFT : I assume that the packaging of a task should be made at some point by the package.js file since the package.json file does not contains the vsts-task-lib which is referenced by the externals.json only. 
1/ But how are we supposed to use this package.js file ? 
2/ Is it for any task created or only the tasks coming from the vso-agent-tasks repo ?

**Comment by bryanmacfarlane** [comment]
That's because tfx is not a build tool.  It's a runtime tool to create and upload.

Xplat tasks are written in typescript by calling the typescript compiler.  We don't dictate what your build tool is.  We happen to use gulp.  some folks use grunt.  some folks use npm.  Some folks write a shellscript to call tsc.  If you use gulp as well, you're free to copy some of our build script.  In the end, you're calling the tsc compiler to call it and you are copying the task-lib into a node_modules folder in the tasks.  That's it.  It's that simple.  Our scripts happen to do a bunch of stuff which is specific to our loc process not sure it's worth you adopting/copy.  Just compile and copy - you're done.

**Comment by LiohAu** [comment]
Ok thanks for the explanation. 
With your help and the contribute.md page I could build the tasks and upload the good one (with the node_modules inside) 

One more thing : when uploading this new task, since in this specific case I didn't bump the version, is there a way to tell the agents to remove the one they probably have cached ? For now I deleted/re-created the agent, but it's not really convenient.

**Comment by bryanmacfarlane** [comment]
No.  The id and version is the identifier of a task.  If it's different it should have a diff version

You should never pick up tasks from master.  They are unreleased.  We have release branches

You should publish built tasks

**Comment by LiohAu** [comment]
I took the m98 branch, Xcode task works perfectly which is not the case with the master branch one (but I'll open another issue for that in the appropriate place)
