### ISSUE TITLE
Please support `tl.GetVariables`

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-task-lib#78]
it's easy to access a single variable, but accessing lists(of) variables and doing matching against variable names is hard. I could query the environment, but then it's hard to distinguish between values stored in the environment and which ones have been added through the build system.

A simple comma delimited list of variables would be welcome. It could simply be one more environment variable which is set when the task is initialized.

**Comment by ericsciple** [comment]
@jessehouwing can you help me understand the use case?

**Comment by jessehouwing** [comment]
I have a bunch of VSTS tasks that can manipulate and validate variables. A colleague of mine has a bunch of tasks that use a postfix/prefix system to perform multiple actions with the given group of variable values.

There are a bunch of original powershell host tasks that make use of the ability to query all variables.

It's also very helpful when debugging, knowing which variables have and have not been defined. Not only as a task author, but also as a build workflow author.

I'd like to be able to distinguish between the Build/Release/Release Environment variables and environment variables that were carried over from the system. Especially with larger build agent pools those can be incredibly hard to debug when the setting is available on one host and not on another. 

Example of one of the requests from a user is to be able to detect whether a bunch of variables have a numeric/have a value value (as currently there's no way to type variables). This is handy when you allow people to set the value at queue time. he's using a naming pattern akin to hungarian notation and would like to be able to mark int_* as having to be of integer value. So I'd like to be able to get all variables with int_* in the name.

**Comment by ericsciple** [comment]
@bryanmacfarlane - thoughts? If we move forward on this one, it seems like we would want to set two lists: one for public variables and one for secret variables.

**Comment by bryanmacfarlane** [comment]
fixed in new agent and new lib
