### ISSUE TITLE
Get-VstsEndpoint for Azure RM Endpoint missing subscription info

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-task-lib#79]
The subscription name/id is missing for an Azure RM Endpoint, looks like it should be `$Endpoint.Data.SubscriptionId` based on [this](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1#L73) task?

code in custom task
```ps1
$ConnectedService = Get-VstsInput -Name ConnectedService -Require
$Endpoint = Get-VstsEndpoint -Name $ConnectedService -Require
"Endpoint:"
$Endpoint | ConvertTo-Json -Depth 32
```

output
```javascript
Endpoint:
{
    "Auth":  {
                 "parameters":  {
                                    "serviceprincipalid":  ********,
                                    "serviceprincipalkey":  ********,
                                    "tenantid":  ********
                                },
                 "scheme":  "ServicePrincipal"
             },
    "Url":  "https://management.core.windows.net/"
}
```

**Comment by ericsciple** [comment]
Are you on Update 2 (1.95)? It looks like Data wasn't added (within agent code) until 1.97.

**Comment by ericsciple** [comment]
I've updated the docs now.

**Comment by gregjhogan** [comment]
Are you referring to TFS Update 2?  I am using VSO and the endpoint was just created yesterday, so that shouldn't be the problem.

**Comment by ericsciple** [comment]
Strange. Are you sure you grabbed a high enough version of the vsts-task-sdk? I know 0.6.2 has the required logic.

**Comment by gregjhogan** [comment]
I ran npm install vsts-task-sdk yesterday, but got version 0.5.4.  Turns out I had npm configured to use a proxy server which it couldn't connect to, and npm installed an old version it had cached on my machine with no indication it failed to connect to the internet ... ugh :(  Now I have 0.6.2 installed and everything is good (Data contains SubscriptionId and SubscriptionName).  Sorry, my bad.

**Comment by ericsciple** [comment]
Cool, thanks for the confirmation. Interesting proxy problem as well, good to know :)
