### ISSUE TITLE
tl.which on Windows should attempt to find the files in this order .exe .bat .cmd

### ISSUE THREAD

**Issue by jpricketMSFT** [Microsoft/vsts-task-lib#82]
Apache ANT task has 3 scripts to run ANT: ant.bat for Windows, ant shell script for _nix, and ant.cmd for OS/2 apparently. Unfortunately, the ant.cmd is in a format that Windows cannot run (it has a /_ */ style comment at the top). And this is exactly the one that gets picked by tl.which on Windows. Changing the order to check for .bat first should fix the problem.

**Comment by AshwiniChalla** [comment]
Similar problem with gradle.

**Comment by nigurr** [comment]
Addressed here: https://github.com/Microsoft/vsts-task-lib/pull/104

**Comment by ericsciple** [comment]
rewrote which: PR https://github.com/Microsoft/vsts-task-lib/pull/231
