### ISSUE TITLE
Writing to process.stderr does not show output in red in build logs

### ISSUE THREAD

**Issue by prmittal** [Microsoft/vsts-task-lib#97]
In build logs, any output written to process.stdout and process.stderr show up as the same. There should be some differentiation there.

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/ErrorsWarningsAndTaskResult.md#external-commands-and-stderr

**Comment by ericsciple** [comment]
The behavior is consistent with powershell.exe
